import type { PublicSourceId } from '@/content/public-sources'
import type { ComplianceRuleDefinition } from '@/lib/compliance/rule-engine'

export const C01_RIE_VERSION = '1.0' as const

export const c01RieQuestions = [
  { code: 'C01-Q01', prompt: 'Beschikt uw organisatie over een schriftelijke RI&E?', helpText: 'Een RI&E mag digitaal zijn, maar moet als document beschikbaar zijn.', inputType: 'SINGLE_SELECT', required: true, options: ['YES','NO','PARTIAL','UNKNOWN'] },
  { code: 'C01-Q02', prompt: 'Heeft de RI&E betrekking op alle relevante werkzaamheden, werkplekken en locaties?', inputType: 'SINGLE_SELECT', required: true, options: ['YES','NO','PARTIAL','UNKNOWN'] },
  { code: 'C01-Q03', prompt: 'Zijn de eerder aangegeven arbeidsrisico\'s in de RI&E meegenomen?', inputType: 'SINGLE_SELECT', required: true, options: ['YES','NO','PARTIAL','UNKNOWN'] },
  { code: 'C01-Q04', prompt: 'Zijn de geïnventariseerde risico\'s ook beoordeeld en geprioriteerd?', inputType: 'SINGLE_SELECT', required: true, options: ['YES','NO','PARTIAL','UNKNOWN'] },
  { code: 'C01-Q05', prompt: 'Hebben sinds de laatste RI&E belangrijke veranderingen plaatsgevonden?', inputType: 'SINGLE_SELECT', required: true, options: ['YES','NO','UNKNOWN'] },
  { code: 'C01-Q05A', prompt: 'Is na die veranderingen beoordeeld of de RI&E moest worden aangepast?', inputType: 'SINGLE_SELECT', required: false, options: ['YES','NO','PARTIAL','UNKNOWN'], visibleWhen: { question: 'C01-Q05', equals: 'YES' } },
  { code: 'C01-Q06', prompt: 'Wanneer is de RI&E voor het laatst inhoudelijk beoordeeld?', inputType: 'SINGLE_SELECT', required: true, options: ['LT_1Y','Y1_2','Y2_5','GT_5Y','UNKNOWN'] },
  { code: 'C01-Q07', prompt: 'Zijn relevante bijzondere groepen medewerkers in de RI&E meegenomen?', inputType: 'SINGLE_SELECT', required: true, options: ['YES','NO','PARTIAL','NOT_APPLICABLE','UNKNOWN'] },
  { code: 'C01-Q08', prompt: 'Is beoordeeld of deskundige toetsing van de RI&E verplicht is?', inputType: 'SINGLE_SELECT', required: true, options: ['YES','NO','UNKNOWN'] },
  { code: 'C01-Q08A', prompt: 'Is de RI&E, wanneer toetsing verplicht is, door de juiste bevoegde deskundige(n) getoetst?', inputType: 'SINGLE_SELECT', required: false, options: ['YES','NO','NOT_APPLICABLE','UNKNOWN'] },
  { code: 'C01-Q09', prompt: 'Is binnen de organisatie een vaste werkwijze afgesproken om de RI&E actueel te houden?', inputType: 'SINGLE_SELECT', required: true, options: ['YES','NO','PARTIAL','UNKNOWN'] },
  { code: 'C01-Q10', prompt: 'Kunnen werknemers kennisnemen van de RI&E en de voor hen relevante risico\'s en maatregelen?', inputType: 'SINGLE_SELECT', required: true, options: ['YES','NO','PARTIAL','UNKNOWN'] },
] as const

export const c01RieSourceIds = ['arbowet-current', 'arbeidsinspectie-rie'] as const satisfies readonly PublicSourceId[]

const rule = (value: ComplianceRuleDefinition) => value

export const c01RieRules: readonly ComplianceRuleDefinition[] = [
  rule({ code:'C01-R01', moduleCode:'C01', condition:{question:'C01-Q01',equals:'NO'}, applicability:'RELEVANT', assessmentStatus:'ACTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_MISSING', findingTitle:'RI&E ontbreekt', findingBody:'U geeft aan dat uw organisatie niet over een schriftelijke RI&E beschikt.', recommendedAction:'Stel een RI&E op waarin de arbeidsrisico\'s binnen uw organisatie worden geïnventariseerd en geëvalueerd.', serviceSuggestionCode:'RIE_SUPPORT', position:1 }),
  rule({ code:'C01-R02', moduleCode:'C01', condition:{question:'C01-Q01',equals:'UNKNOWN'}, applicability:'RELEVANT', assessmentStatus:'ATTENTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_UNKNOWN', findingTitle:'Niet vastgesteld of een RI&E aanwezig is', findingBody:'Op basis van uw antwoord kan niet worden vastgesteld of een RI&E aanwezig is.', recommendedAction:'Controleer of een actuele RI&E aanwezig is.', position:2 }),
  rule({ code:'C01-R03', moduleCode:'C01', condition:{question:'C01-Q02',equals:'NO'}, applicability:'RELEVANT', assessmentStatus:'ACTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_SCOPE_INCOMPLETE', findingTitle:'RI&E dekt niet de hele organisatie', findingBody:'Niet alle relevante werkzaamheden, werkplekken of locaties zijn volgens uw antwoord meegenomen.', recommendedAction:'Breid de RI&E uit met de ontbrekende werkzaamheden, werkplekken of locaties.', position:3 }),
  rule({ code:'C01-R04', moduleCode:'C01', condition:{question:'C01-Q03',equals:'NO'}, applicability:'RELEVANT', assessmentStatus:'ACTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_RISKS_INCOMPLETE', findingTitle:'Bekende arbeidsrisico\'s ontbreken in de RI&E', findingBody:'Eén of meer eerder aangegeven arbeidsrisico\'s zijn volgens uw antwoord niet in de RI&E opgenomen.', recommendedAction:'Neem de ontbrekende arbeidsrisico\'s op en beoordeel deze in de RI&E.', position:4 }),
  rule({ code:'C01-R05', moduleCode:'C01', condition:{question:'C01-Q04',equals:'NO'}, applicability:'RELEVANT', assessmentStatus:'ACTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_NOT_EVALUATED', findingTitle:'Risico\'s zijn onvoldoende geëvalueerd', findingBody:'De geïnventariseerde risico\'s zijn volgens uw antwoord niet voldoende beoordeeld en geprioriteerd.', recommendedAction:'Beoordeel ernst en blootstelling en bepaal welke risico\'s als eerste moeten worden aangepakt.', position:5 }),
  rule({ code:'C01-R06', moduleCode:'C01', condition:{all:[{question:'C01-Q05',equals:'YES'},{question:'C01-Q05A',equals:'NO'}]}, applicability:'RELEVANT', assessmentStatus:'ACTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_CHANGE_NOT_REVIEWED', findingTitle:'RI&E mogelijk niet meer actueel', findingBody:'Er zijn relevante veranderingen geweest, maar de RI&E is daarna niet opnieuw beoordeeld.', recommendedAction:'Beoordeel de RI&E opnieuw en actualiseer deze waar nodig.', position:6 }),
  rule({ code:'C01-R07', moduleCode:'C01', condition:{question:'C01-Q06',equals:'GT_5Y'}, applicability:'RELEVANT', assessmentStatus:'ATTENTION_REQUIRED', priority:'NORMAL', assessmentMode:'FULL', findingCode:'RIE_REVIEW_OLD', findingTitle:'RI&E is langere tijd niet inhoudelijk beoordeeld', findingBody:'Er geldt geen algemene wettelijke vervaldatum, maar een langere periode zonder inhoudelijke beoordeling is aanleiding om de actualiteit te controleren.', recommendedAction:'Controleer of de RI&E nog aansluit op de huidige werkzaamheden, locaties en risico\'s.', position:7 }),
  rule({ code:'C01-R08', moduleCode:'C01', condition:{question:'C01-Q07',equals:'NO'}, applicability:'RELEVANT', assessmentStatus:'ACTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_SPECIAL_GROUPS_MISSING', findingTitle:'Bijzondere groepen onvoldoende meegenomen', findingBody:'Relevante bijzondere groepen zijn volgens uw antwoord niet in de RI&E meegenomen.', recommendedAction:'Neem de specifieke risico\'s voor relevante bijzondere groepen op in de RI&E.', position:8 }),
  rule({ code:'C01-R09', moduleCode:'C01', condition:{question:'C01-Q08',equals:'NO'}, applicability:'RELEVANT', assessmentStatus:'ATTENTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_TEST_REQUIREMENT_UNKNOWN', findingTitle:'Toetsingsplicht niet beoordeeld', findingBody:'Niet is beoordeeld of deskundige toetsing van de RI&E verplicht is.', recommendedAction:'Bepaal of voor uw organisatie deskundige toetsing vereist is en leg de uitkomst vast.', position:9 }),
  rule({ code:'C01-R10', moduleCode:'C01', condition:{question:'C01-Q08A',equals:'NO'}, applicability:'RELEVANT', assessmentStatus:'ACTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_TESTING_INADEQUATE', findingTitle:'Vereiste toetsing niet goed geregeld', findingBody:'U geeft aan dat verplichte toetsing niet door de juiste bevoegde deskundige(n) is uitgevoerd.', recommendedAction:'Laat de RI&E waar vereist toetsen door deskundigen met passende bevoegdheid en expertise.', serviceSuggestionCode:'RIE_REVIEW', position:10 }),
  rule({ code:'C01-R11', moduleCode:'C01', condition:{question:'C01-Q09',equals:'NO'}, applicability:'RELEVANT', assessmentStatus:'ATTENTION_REQUIRED', priority:'NORMAL', assessmentMode:'FULL', findingCode:'RIE_GOVERNANCE_WEAK', findingTitle:'Actualisatieproces is niet geborgd', findingBody:'Er lijkt geen vaste werkwijze te zijn om de RI&E actueel te houden.', recommendedAction:'Leg vast wanneer en door wie wordt beoordeeld of wijzigingen aanpassing van de RI&E vereisen.', position:11 }),
  rule({ code:'C01-R12', moduleCode:'C01', condition:{question:'C01-Q10',equals:'NO'}, applicability:'RELEVANT', assessmentStatus:'ACTION_REQUIRED', priority:'HIGH', assessmentMode:'FULL', findingCode:'RIE_NOT_ACCESSIBLE', findingTitle:'RI&E is niet toegankelijk voor werknemers', findingBody:'Werknemers kunnen volgens uw antwoord geen kennisnemen van de RI&E en relevante risico\'s en maatregelen.', recommendedAction:'Maak de RI&E en relevante informatie toegankelijk voor werknemers.', position:12 }),
  rule({ code:'C01-R99', moduleCode:'C01', condition:{all:[{question:'C01-Q01',equals:'YES'},{question:'C01-Q02',equals:'YES'},{question:'C01-Q03',equals:'YES'},{question:'C01-Q04',equals:'YES'},{any:[{question:'C01-Q05',equals:'NO'},{question:'C01-Q05A',equals:'YES'}]},{any:[{question:'C01-Q07',equals:'YES'},{question:'C01-Q07',equals:'NOT_APPLICABLE'}]},{question:'C01-Q08',equals:'YES'},{any:[{question:'C01-Q08A',equals:'YES'},{question:'C01-Q08A',equals:'NOT_APPLICABLE'}]},{question:'C01-Q09',equals:'YES'},{question:'C01-Q10',equals:'YES'}]}, applicability:'RELEVANT', assessmentStatus:'IN_ORDER', priority:'LOW', assessmentMode:'FULL', position:99 }),
]

export const c01RieRequiredQuestionCodes = c01RieQuestions.filter((q) => q.required).map((q) => q.code)
