export const COMPLIANCE_FREE_INTAKE_VERSION = '1.0' as const

export const complianceFreeIntakeQuestions = [
  {
    code: 'FI-01',
    prompt: 'Heeft uw organisatie werknemers in dienst?',
    inputType: 'SINGLE_SELECT',
    required: true,
    options: ['YES', 'NO', 'UNKNOWN'],
  },
  {
    code: 'FI-02',
    prompt: 'Hoeveel werknemers werken er ongeveer binnen de organisatie?',
    inputType: 'SINGLE_SELECT',
    required: true,
    options: ['ONE_TO_25', 'MORE_THAN_25', 'UNKNOWN'],
  },
  {
    code: 'FI-03',
    prompt: 'Werken medewerkers structureel thuis, op meerdere locaties of op locaties van anderen?',
    inputType: 'MULTI_SELECT',
    required: true,
    options: ['HOME', 'MULTIPLE_LOCATIONS', 'THIRD_PARTY_LOCATIONS', 'NONE', 'UNKNOWN'],
  },
  {
    code: 'FI-04',
    prompt: 'Worden machines, arbeidsmiddelen, voertuigen of mobiele werktuigen gebruikt?',
    inputType: 'MULTI_SELECT',
    required: true,
    options: ['MACHINES', 'WORK_EQUIPMENT', 'VEHICLES', 'NONE', 'UNKNOWN'],
  },
  {
    code: 'FI-05',
    prompt: 'Komen gevaarlijke stoffen, biologische agentia of mogelijk explosieve atmosferen voor?',
    inputType: 'MULTI_SELECT',
    required: true,
    options: ['HAZARDOUS_SUBSTANCES', 'BIOLOGICAL_AGENTS', 'ATEX', 'NONE', 'UNKNOWN'],
  },
  {
    code: 'FI-06',
    prompt: 'Komt fysieke belasting, beeldschermwerk of een bijzondere werkplekinrichting voor?',
    inputType: 'MULTI_SELECT',
    required: true,
    options: ['PHYSICAL_LOAD', 'DISPLAY_SCREEN', 'WORKPLACE_SETUP', 'NONE', 'UNKNOWN'],
  },
  {
    code: 'FI-07',
    prompt: 'Komen werkdruk, agressie, geweld, pesten, discriminatie of ander ongewenst gedrag als risico voor?',
    inputType: 'SINGLE_SELECT',
    required: true,
    options: ['YES', 'NO', 'UNKNOWN'],
  },
  {
    code: 'FI-08',
    prompt: 'Komen geluid, trillingen, extreme warmte/koude of andere belastende omgevingsfactoren voor?',
    inputType: 'MULTI_SELECT',
    required: true,
    options: ['NOISE', 'VIBRATION', 'CLIMATE', 'NONE', 'UNKNOWN'],
  },
  {
    code: 'FI-09',
    prompt: 'Wordt gewerkt op hoogte, met elektrotechnische risico\'s, drukapparatuur of straling?',
    inputType: 'MULTI_SELECT',
    required: true,
    options: ['HEIGHT', 'ELECTRICAL', 'PRESSURE', 'RADIATION', 'NONE', 'UNKNOWN'],
  },
  {
    code: 'FI-10',
    prompt: 'Komt alleenwerk, nachtwerk, ploegendienst of afwijkende werktijden voor?',
    inputType: 'MULTI_SELECT',
    required: true,
    options: ['LONE_WORK', 'NIGHT_OR_SHIFT', 'NONE', 'UNKNOWN'],
  },
  {
    code: 'FI-11',
    prompt: 'Werken binnen de organisatie jongeren onder 18 jaar?',
    inputType: 'SINGLE_SELECT',
    required: true,
    options: ['YES', 'NO', 'UNKNOWN'],
  },
  {
    code: 'FI-12',
    prompt: 'Is er werk waarbij zwangerschap of borstvoeding aanleiding kan geven tot aanvullende arbeidsrisico\'s of maatregelen?',
    inputType: 'SINGLE_SELECT',
    required: true,
    options: ['YES', 'NO', 'UNKNOWN'],
  },
  {
    code: 'FI-13',
    prompt: 'Is er een RI&E aanwezig?',
    inputType: 'SINGLE_SELECT',
    required: true,
    options: ['YES', 'NO', 'UNKNOWN'],
  },
  {
    code: 'FI-14',
    prompt: 'Zijn Plan van Aanpak, preventiemedewerker en arbodienstverlening binnen de organisatie geregeld?',
    inputType: 'SINGLE_SELECT',
    required: true,
    options: ['YES', 'PARTIAL', 'NO', 'UNKNOWN'],
  },
  {
    code: 'FI-15',
    prompt: 'Zijn BHV en werknemersbetrokkenheid bij arbozaken binnen de organisatie geregeld?',
    inputType: 'SINGLE_SELECT',
    required: true,
    options: ['YES', 'PARTIAL', 'NO', 'UNKNOWN'],
  },
] as const

export type ComplianceFreeIntakeQuestion = (typeof complianceFreeIntakeQuestions)[number]

export const complianceFreeIntakeModuleTitles = {
  C01: 'RI&E',
  C02: 'Plan van Aanpak',
  C03: 'Preventiemedewerker',
  C04: 'Basiscontract & arbodienstverlening',
  C05: 'BHV & noodorganisatie',
  C06: 'PAGO / arbeidsgezondheidskundig onderzoek',
  C07: 'Ziekteverzuimbeleid',
  C08: 'Voorlichting, instructie & toezicht',
  C09: 'Arbeidsongevallen & incidenten',
  C10: 'Werknemersparticipatie',
  R01: 'Arbeidsmiddelen & machines',
  R02: 'Persoonlijke beschermingsmiddelen',
  R03: 'Gevaarlijke stoffen',
  R04: 'Fysieke belasting',
  R05: 'Beeldscherm-, kantoor- & thuiswerk',
  R06: 'Psychosociale arbeidsbelasting',
  R07: 'Geluid',
  R08: 'Trillingen',
  R09: 'Werken op hoogte',
  R10: 'Jongeren',
  R11: 'Zwangerschap & borstvoeding',
  R12: 'Biologische agentia',
  R13: 'Alleenwerk',
  R14: 'Nacht-, ploeg- & afwijkende werktijden',
  R15: 'Werken op locaties van derden',
  R16: 'Verkeer & voertuigen',
  R17: 'Klimaat & fysieke werkomgeving',
  R18: 'Werkplekinrichting',
  R19: 'Brand- & explosierisico',
  R20: 'Elektrotechnische risico\'s',
  R21: 'Straling',
  R22: 'Drukapparatuur, drukvaten & perslucht',
  R23: 'Explosieve atmosferen / ATEX',
} as const

export type ComplianceModuleCode = keyof typeof complianceFreeIntakeModuleTitles
