export const complianceFrameworkV1 = {
  frameworkCode: 'NL_ARBO',
  version: '2026-10',
  title: 'WorkMatchr Arbo Compliance Scan',
  methodology:
    'Versioneerbare, deterministische beoordeling van geselecteerde Nederlandse arbo-onderwerpen op basis van zelfverklaring. Applicability, beoordelingsstatus, prioriteit en assessment mode blijven afzonderlijke dimensies.',
  disclaimer:
    'De scan beoordeelt geselecteerde arbo-onderwerpen op basis van door de gebruiker verstrekte informatie. De scan vervangt geen formele RI&E, Plan van Aanpak, wettelijke keuring, inspectie, meting, specialistische beoordeling of certificering.',
  modules: [
    ['C01', 'RI&E', 'CORE', 'FULL'],
    ['C02', 'Plan van Aanpak', 'CORE', 'FULL'],
    ['C03', 'Preventiemedewerker', 'CORE', 'FULL'],
    ['C04', 'Basiscontract & arbodienstverlening', 'CORE', 'FULL'],
    ['C05', 'BHV & noodorganisatie', 'CORE', 'FULL'],
    ['C06', 'PAGO / arbeidsgezondheidskundig onderzoek', 'CORE', 'FULL'],
    ['C07', 'Ziekteverzuimbeleid', 'CORE', 'FULL'],
    ['C08', 'Voorlichting, instructie & toezicht', 'CORE', 'FULL'],
    ['C09', 'Arbeidsongevallen & incidenten', 'CORE', 'FULL'],
    ['C10', 'Werknemersparticipatie', 'CORE', 'FULL'],
    ['R01', 'Arbeidsmiddelen & machines', 'RISK', 'SCREENING'],
    ['R02', 'Persoonlijke beschermingsmiddelen', 'RISK', 'FULL'],
    ['R03', 'Gevaarlijke stoffen', 'RISK', 'SCREENING'],
    ['R04', 'Fysieke belasting', 'RISK', 'SCREENING'],
    ['R05', 'Beeldscherm-, kantoor- & thuiswerk', 'RISK', 'FULL'],
    ['R06', 'Psychosociale arbeidsbelasting', 'RISK', 'FULL'],
    ['R07', 'Geluid', 'RISK', 'SCREENING'],
    ['R08', 'Trillingen', 'RISK', 'SCREENING'],
    ['R09', 'Werken op hoogte', 'RISK', 'SCREENING'],
    ['R10', 'Jongeren', 'RISK', 'FULL'],
    ['R11', 'Zwangerschap & borstvoeding', 'RISK', 'FULL'],
    ['R12', 'Biologische agentia', 'RISK', 'SCREENING'],
    ['R13', 'Alleenwerk', 'RISK', 'FULL'],
    ['R14', 'Nacht-, ploeg- & afwijkende werktijden', 'RISK', 'FULL'],
    ['R15', 'Werken op locaties van derden', 'RISK', 'FULL'],
    ['R16', 'Verkeer & voertuigen', 'RISK', 'SCREENING'],
    ['R17', 'Klimaat & fysieke werkomgeving', 'RISK', 'SCREENING'],
    ['R18', 'Werkplekinrichting', 'RISK', 'FULL'],
    ['R19', 'Brand- & explosierisico', 'RISK', 'SCREENING'],
    ['R20', 'Elektrotechnische risico\'s', 'RISK', 'SCREENING'],
    ['R21', 'Straling', 'RISK', 'SCREENING'],
    ['R22', 'Drukapparatuur, drukvaten & perslucht', 'RISK', 'SCREENING'],
    ['R23', 'Explosieve atmosferen / ATEX', 'RISK', 'SPECIALIST_REQUIRED'],
  ] as const,
} as const

export type ComplianceFrameworkModuleSeed = (typeof complianceFrameworkV1.modules)[number]
