import type { Metadata } from 'next'
import { Section } from '@/components/layout/section'
import { Heading } from '@/components/ui/heading'
import { Text } from '@/components/ui/text'
import { PublicContentCard } from '@/components/public/public-content-card'
import { PublicOverviewGrid } from '@/components/public/public-overview-grid'
import { PublicPageLayout } from '@/components/public/public-page-layout'
import { PublicContentPathways } from '@/components/public/public-content-pathways'
import { knowledgeCategories } from '@/content/public-overviews'

export const metadata: Metadata = { title: 'Kenniscentrum gezond en veilig werken | WorkMatchr', description: 'Betrouwbare uitleg over arbeidsomstandigheden, veiligheid en gezondheid.', alternates: { canonical: '/kenniscentrum' }, openGraph: { title: 'Kenniscentrum | WorkMatchr', description: 'Betrouwbare uitleg over arbeidsomstandigheden, veiligheid en gezondheid.', url: '/kenniscentrum' } }

export default function KnowledgeCenterPage() {
  return <PublicPageLayout breadcrumbs={[{ label: 'Home', href: '/' }, { label: 'Kenniscentrum' }]} eyebrow="Kenniscentrum" title="Betrouwbare uitleg begint bij uw vraag" description="Vind zorgvuldig onderbouwde informatie en zie duidelijk het verschil tussen uitleg, wettelijke context en dienstverlening."><Section spacing="compact" containerClassName="space-y-12"><div><label htmlFor="knowledge-search" className="font-semibold">Zoeken in het kenniscentrum</label><div className="mt-3 max-w-2xl"><input id="knowledge-search" type="search" disabled placeholder="Zoeken wordt voorbereid" className="w-full rounded-control border border-border bg-surface-subtle px-4 py-3 text-text-secondary disabled:cursor-not-allowed" /><Text size="sm" className="mt-2 text-text-secondary">Zoeken en filteren zijn nog niet beschikbaar. Gebruik voorlopig de categorieën en het gepubliceerde onderwerp hieronder.</Text></div></div><section aria-labelledby="published-title"><Heading as="h2" size="h2" id="published-title">Nu gepubliceerd</Heading><div className="mt-6 max-w-2xl"><PublicContentCard title="Moet ik een RI&E hebben?" description="Een vraaggestuurde uitleg met wettelijke context, uitzonderingssituaties en officiële bronnen." href="/kenniscentrum/moet-ik-een-rie-hebben" linkLabel="Lees de uitleg" status="Uitleg · bronnen gecontroleerd" /></div></section><section aria-labelledby="categories-title"><Heading as="h2" size="h2" id="categories-title">Categorieën</Heading><div className="mt-6"><PublicOverviewGrid items={knowledgeCategories} /></div></section><section aria-labelledby="types-title"><Heading as="h2" size="h2" id="types-title">Drie soorten informatie</Heading><div className="mt-6 grid gap-5 md:grid-cols-3"><PublicContentCard title="Uitleg" description="Een begrijpelijk antwoord op een praktische vraag." /><PublicContentCard title="Wettelijke verplichting" description="Algemene wettelijke context met herleidbare bronnen." /><PublicContentCard title="Dienstverlening" description="Wat deskundige ondersteuning kan inhouden en wanneer die nuttig kan zijn." /></div></section></Section><PublicContentPathways contentId="overview:knowledge" /></PublicPageLayout>
}
