import { Text } from '@/components/ui/text'
import type { ObligationContent } from '@/content/public-content-model'
import { publicRoutes } from '@/content/public-routes'
import { EvidencePanel } from './evidence-panel'
import { PublicPageLayout } from './public-page-layout'
import { PublicBulletList, PublicContentStatus, PublicDetailBody, PublicDetailEnding, PublicFaqList, PublicTextSection, shouldDisplayPublicFaq } from './public-detail-shared'

export function ObligationDetailPage({ content }: { content: ObligationContent }) {
  return <PublicPageLayout breadcrumbs={[{ label: 'Home', href: publicRoutes.home }, { label: 'Wettelijke verplichtingen', href: publicRoutes.obligations }, { label: content.title }]} eyebrow="Wettelijke verplichting" title={content.title} description={content.summary}><PublicDetailBody><PublicContentStatus content={content} /><PublicTextSection id="inhoud" title="Wat houdt de verplichting in?"><Text>{content.explanation}</Text></PublicTextSection><PublicTextSection id="toepassing" title="Voor wie kan deze gelden?"><Text>{content.potentiallyRelevantFor}</Text></PublicTextSection><PublicTextSection id="praktijk" title="Wat moet een organisatie praktisch regelen?"><PublicBulletList items={content.practicalActions} /></PublicTextSection><PublicTextSection id="nuance" title="Welke context of uitzonderingen zijn relevant?"><PublicBulletList items={content.nuances} /></PublicTextSection><PublicTextSection id="verantwoordelijkheid" title="Wie heeft welke verantwoordelijkheid?"><Text>{content.responsibilities}</Text></PublicTextSection><PublicTextSection id="rie" title="Hoe hangt dit samen met de RI&E?"><Text>{content.rieRelationship}</Text></PublicTextSection><PublicTextSection id="ondersteuning" title="Welke ondersteuning kan passend zijn?"><Text>{content.suitableSupport}</Text></PublicTextSection>{shouldDisplayPublicFaq(content.id) ? <PublicFaqList faq={content.faq} /> : null}<PublicTextSection id="basis" title="Wettelijke basis"><Text>{content.legalBasis}</Text><Text>{content.disclaimer}</Text></PublicTextSection><PublicDetailEnding contentId={content.id} sourceIds={content.sourceIds} sourceSupplement={<EvidencePanel />} /></PublicDetailBody></PublicPageLayout>
}
