import type { PublicSource } from './public-content-model'

export const publicSources = {
  'arbowet-current': {
    id: 'arbowet-current',
    title: 'Arbeidsomstandighedenwet',
    publisher: 'Overheid.nl',
    url: 'https://wetten.overheid.nl/arbowet',
    type: 'LAW',
    evidenceLevel: 'PRIMARY',
    reviewedAt: '2026-07-19',
    note: 'Primaire wettelijke bron voor arbobeleid, RI&E, voorlichting, ongevallen, deskundige bijstand, BHV en PAGO.',
  },
  'rijksoverheid-arbowet': {
    id: 'rijksoverheid-arbowet',
    title: 'Waar moet mijn werkgever voor zorgen volgens de Arbowet?',
    publisher: 'Rijksoverheid',
    url: 'https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsomstandigheden/waar-moet-mijn-werkgever-voor-zorgen-volgens-de-arbowet',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-07-19',
    note: 'Officiële publieksuitleg over de hoofdelementen van arbobeleid.',
  },
  'arbeidsinspectie-rie': {
    id: 'arbeidsinspectie-rie',
    title: 'Risico-inventarisatie en -evaluatie en plan van aanpak',
    publisher: 'Nederlandse Arbeidsinspectie',
    url: 'https://www.nlarbeidsinspectie.nl/onderwerpen/arbeidsomstandighedenwet/risico-inventarisatie-evaluatie-en-plan-van-aanpak',
    type: 'ENFORCEMENT_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-07-19',
    note: 'Officiële uitleg over RI&E, plan van aanpak en toetsing.',
  },
  'arboportaal-preventiemedewerker': {
    id: 'arboportaal-preventiemedewerker',
    title: 'Wat zegt de wet over de preventiemedewerker?',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/ondersteuning-bij-arbowet/preventiemedewerker/wat-zegt-de-wet-over-de-preventiemedewerker',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-07-19',
    note: 'Officiële uitleg over positie, taken en samenwerking van de preventiemedewerker.',
  },
  'arbeidsinspectie-preventiemedewerker': {
    id: 'arbeidsinspectie-preventiemedewerker',
    title: 'Preventiemedewerkers',
    publisher: 'Nederlandse Arbeidsinspectie',
    url: 'https://www.nlarbeidsinspectie.nl/onderwerpen/arbeidsomstandighedenwet/preventiemedewerkers',
    type: 'ENFORCEMENT_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-09-21',
    note: 'Actuele officiële uitleg over de interne positie, RI&E-betrokkenheid en dagelijkse rol van de preventiemedewerker.',
  },
  'arboportaal-arbozorg-organisatie': {
    id: 'arboportaal-arbozorg-organisatie',
    title: 'Uitvoering Arbowet in de organisatie',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/arbowet--en--regelgeving/arbowetgeving/uitvoering-arbowet-in-de-organisatie',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-09-21',
    note: 'Officiële uitleg over samenwerking, medezeggenschap en de persoon en positie van de preventiemedewerker.',
  },
  'arboportaal-bedrijfsarts': {
    id: 'arboportaal-bedrijfsarts',
    title: 'Bedrijfsarts',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/ondersteuning-bij-arbowet/bedrijfsarts',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-07-19',
    note: 'Officiële uitleg over de onafhankelijke rol en toegankelijkheid van de bedrijfsarts.',
  },
  'arboportaal-basiscontract': {
    id: 'arboportaal-basiscontract',
    title: 'Waar moet het basiscontract aan voldoen?',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/ondersteuning-bij-arbowet/basiscontract/waar-moet-het-basiscontract-aan-voldoen',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-07-19',
    note: 'Officiële uitleg over de minimale afspraken voor arbodienstverlening.',
  },
  'arboportaal-pago': {
    id: 'arboportaal-pago',
    title: 'PAGO (Periodiek Arbeidsgezondheidskundig Onderzoek)',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/arbowet--en--regelgeving/arbobeleid/pago',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-07-19',
    note: 'Officiële uitleg over PAGO, de relatie met RI&E en het onderscheid met breder PMO.',
  },
  'arboportaal-psa-batch2': {
    id: 'arboportaal-psa-batch2',
    title: 'Psychosociale arbeidsbelasting (PSA)',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/psychosociale-arbeidsbelasting',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-09-22',
    note: 'Officiële uitleg over PSA, werkdruk, ongewenst gedrag en de verwijzing naar artikel 2.15 van het Arbobesluit.',
  },
  'arboportaal-kerndeskundigen-batch2': {
    id: 'arboportaal-kerndeskundigen-batch2',
    title: 'Arbodeskundigen (kerndeskundigen)',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/ondersteuning-bij-arbowet/arbodeskundigen-kerndeskundigen',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-09-22',
    note: 'Officiële uitleg over kerndeskundigen en hun aanvullende expertise binnen de arbodienstverlening.',
  },
  'arboportaal-blootstellingsmeting-batch2': {
    id: 'arboportaal-blootstellingsmeting-batch2',
    title: 'Blootstellingsmeting van gevaarlijke stoffen',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/werken-met-gevaarlijke-stoffen/blootstellingsmeting',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-09-22',
    note: 'Officiële uitleg over blootstellingsroutes, beoordeling van aard, mate en duur, meet- en schattingsmethoden en toepasselijke waarden.',
  },
  'arbeidsinspectie-ongevallen': {
    id: 'arbeidsinspectie-ongevallen',
    title: 'Arbeidsongevallen',
    publisher: 'Nederlandse Arbeidsinspectie',
    url: 'https://www.nlarbeidsinspectie.nl/onderwerpen/arbeidsomstandighedenwet/arbeidsongevallen',
    type: 'ENFORCEMENT_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-07-19',
    note: 'Actuele officiële uitleg over melding, registratie en leren van arbeidsongevallen.',
  },
  'arbeidsinspectie-ongevalsonderzoek-batch2': {
    id: 'arbeidsinspectie-ongevalsonderzoek-batch2',
    title: 'Ongevalsonderzoek',
    publisher: 'Nederlandse Arbeidsinspectie',
    url: 'https://www.nlarbeidsinspectie.nl/onderwerpen/arbeidsomstandighedenwet/ongevalsonderzoek',
    type: 'ENFORCEMENT_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-09-22',
    note: 'Actuele officiële uitleg over werkgeversrapportage, onderzoek door de Arbeidsinspectie, samenwerking en het bewaren van de ongevalssituatie.',
  },
  'arbeidsinspectie-sectoren': {
    id: 'arbeidsinspectie-sectoren',
    title: 'Sector- en beroepeninformatie Inspectiebrede Risicoanalyse',
    publisher: 'Nederlandse Arbeidsinspectie',
    url: 'https://www.nlarbeidsinspectie.nl/documenten/2026/07/03/sector-en-beroepeninformatie-inspectiebrede-risicoanalyse',
    type: 'OFFICIAL_RESEARCH',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-07-19',
    note: 'Officiële sector- en beroepeninformatie; indicatoren zijn richtinggevend en moeten met andere informatie worden gecombineerd.',
  },
  'arboportaal-arbobeleid': {
    id: 'arboportaal-arbobeleid',
    title: 'Arbobeleid',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/arbowet--en--regelgeving/arbobeleid',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-07-19',
    note: 'Overzicht van wettelijke arbozorg, deskundigheid en preventieve instrumenten.',
  },
  'arboportaal-werknemersraadpleging-2026': {
    id: 'arboportaal-werknemersraadpleging-2026',
    title: 'Regels voor raadpleging van werknemers aangepast per 1 juli 2026',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/actueel/nieuws/2026/06/29/regels-voor-raadpleging-van-werknemers-aangepast-per-1-juli-2026',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-08-20',
    note: 'Officiële uitleg over de vanaf 1 juli 2026 geldende raadpleging van werknemers over het arbobeleid.',
  },
  'arboportaal-bhv': {
    id: 'arboportaal-bhv',
    title: 'Wat zegt de wet over bedrijfshulpverlening?',
    publisher: 'Arboportaal',
    url: 'https://www.arboportaal.nl/onderwerpen/arbozorg/bedrijfshulpverlening/wat-zegt-de-wet-over-bedrijfshulpverlening',
    type: 'OFFICIAL_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-08-21',
    note: 'Officiële uitleg over risicogerichte organisatie, aantal en inzetbaarheid van bedrijfshulpverleners.',
  },
  'arbeidsinspectie-bhv-2025': {
    id: 'arbeidsinspectie-bhv-2025',
    title: 'Werkinstructie bedrijfshulpverlening',
    publisher: 'Nederlandse Arbeidsinspectie',
    url: 'https://www.nlarbeidsinspectie.nl/documenten/2025/07/03/werkinstructie-bedrijfshulpverlening',
    type: 'ENFORCEMENT_GUIDANCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-08-21',
    note: 'Actuele inspectiewerkwijze voor de beoordeling van een risicogerichte BHV-organisatie.',
  },
  'ai-10-bhv-2001': {
    id: 'ai-10-bhv-2001',
    title: 'AI-10 — Bedrijfshulpverlening',
    publisher: 'Sdu Uitgevers',
    url: 'https://www.sdu.nl/shop/sdu-hse-online-arbo-praktijkinformatie-en-regelgeving.html',
    type: 'PROFESSIONAL_REFERENCE',
    evidenceLevel: 'AUTHORITATIVE',
    reviewedAt: '2026-08-21',
    note: 'Historische vakinhoudelijke bron uit 2001 voor scenario’s, organisatie, opleiding, oefenen en evalueren; geen actuele wettelijke grondslag.',
  },
  'arboportaal-beeldschermwerk-catalog': { id: 'arboportaal-beeldschermwerk-catalog', title: 'Beeldschermwerk', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/fysieke-belasting/computerwerk', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over fysieke belasting en werkplekinrichting bij beeldschermwerk.' },
  'arboportaal-arbeidsmiddelen-catalog': { id: 'arboportaal-arbeidsmiddelen-catalog', title: 'Arbeidsmiddelen', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/veiligheid-op-het-werk/arbeidsmiddelen', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over veilig gebruik van arbeidsmiddelen en machines.' },
  'arboportaal-gevaarlijke-stoffen-catalog': { id: 'arboportaal-gevaarlijke-stoffen-catalog', title: 'Gevaarlijke stoffen', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/inrichting-werkvloer/gevaarlijke-stoffen', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over risico’s van gevaarlijke stoffen op het werk.' },
  'arboportaal-opslag-gevaarlijke-stoffen-catalog': { id: 'arboportaal-opslag-gevaarlijke-stoffen-catalog', title: 'Opslag van gevaarlijke stoffen', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/werken-met-gevaarlijke-stoffen/opslag', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over veilige opslag, relevante scenario’s en relatie met RI&E en BHV.' },
  'arboportaal-etikettering-catalog': { id: 'arboportaal-etikettering-catalog', title: 'Etikettering van gevaarlijke stoffen', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/werken-met-gevaarlijke-stoffen/etikettering', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over gevarenetiketten en veiligheidsinformatie.' },
  'arboportaal-atex-catalog': { id: 'arboportaal-atex-catalog', title: 'Explosieveiligheid/ATEX', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/werken-met-gevaarlijke-stoffen/explosieveiligheid-atex', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over explosieve atmosferen, risicoanalyse en explosieveiligheidsdocument.' },
  'arboportaal-brandpreventie-catalog': { id: 'arboportaal-brandpreventie-catalog', title: 'Brandpreventie', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/veiligheid-op-het-werk/brandveiligheid/brandpreventie', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over brandpreventie, vluchten en bedrijfshulpverlening.' },
  'arboportaal-geluid-catalog': { id: 'arboportaal-geluid-catalog', title: 'Lawaai op het werk', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/fysische-factoren/geluid', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over schadelijk geluid en beheersmaatregelen.' },
  'arboportaal-ioniserende-straling-catalog': { id: 'arboportaal-ioniserende-straling-catalog', title: 'Verplichtingen bij ioniserende straling', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/fysische-factoren/ioniserende-straling/verplichtingen-voor-de-werkgever', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over stralingsbescherming en vereiste deskundige rollen.' },
  'arboportaal-stralingsopleiding-catalog': { id: 'arboportaal-stralingsopleiding-catalog', title: 'Opleiding van medewerkers bij stralingswerk', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/fysische-factoren/ioniserende-straling/opleiding-van-medewerkers', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over toepassingsspecifieke opleiding en deskundigheid.' },
  'arboportaal-vertrouwenspersoon-catalog': { id: 'arboportaal-vertrouwenspersoon-catalog', title: 'Vertrouwenspersoon', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/ondersteuning-bij-arbowet/vertrouwenspersoon', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële uitleg over rol en grenzen van vertrouwenspersonen bij ongewenst gedrag.' },
  'arboportaal-ziekteverzuim-catalog': { id: 'arboportaal-ziekteverzuim-catalog', title: 'Ziekteverzuimbeleid', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/ziekteverzuimbeleid', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële informatie over procesmatige begeleiding en de rol van een casemanager.' },
  'arboportaal-reintegratie-catalog': { id: 'arboportaal-reintegratie-catalog', title: 'Re-integratietraject', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/verzuim-en-re-integratie/re-integratie-en-wet-verbetering-poortwachter/re-integratietraject', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële uitleg over rollen van werkgever, werknemer en bedrijfsarts bij re-integratie.' },
  'arboportaal-keuring-arbeidsmiddelen-catalog': { id: 'arboportaal-keuring-arbeidsmiddelen-catalog', title: 'Keuring van arbeidsmiddelen', publisher: 'Arboportaal', url: 'https://www.arboportaal.nl/onderwerpen/veiligheid-op-het-werk/arbeidsmiddelen/keuring-van-arbeidsmiddelen', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Officiële uitleg over wanneer arbeidsmiddelen worden gekeurd en wie dat mag uitvoeren.' },
  'rvo-vertrouwenspersoon-voorstel': { id: 'rvo-vertrouwenspersoon-voorstel', title: 'Vertrouwenspersoon wordt verplicht', publisher: 'Rijksdienst voor Ondernemend Nederland', url: 'https://ondernemersplein.overheid.nl/wetswijzigingen/vertrouwenspersoon-verplicht/', type: 'OFFICIAL_GUIDANCE', evidenceLevel: 'AUTHORITATIVE', reviewedAt: '2026-09-24', note: 'Overheidsinformatie meldt een voorgestelde aanwijsplicht en vermeldt dat de ingangsdatum nog niet bekend is.' },
} as const satisfies Record<string, PublicSource>

export type PublicSourceId = keyof typeof publicSources

export function resolvePublicSources(sourceIds: readonly string[]): readonly PublicSource[] {
  return sourceIds.map((sourceId) => {
    const source = publicSources[sourceId as PublicSourceId]
    if (!source) throw new Error(`Onbekende publieke bron: ${sourceId}`)
    return source
  })
}

export function validatePublicSources(): string[] {
  const issues: string[] = []
  const sources: readonly PublicSource[] = Object.values(publicSources)
  if (new Set(sources.map((source) => source.id)).size !== sources.length) issues.push('Bron-ID’s moeten uniek zijn.')
  for (const source of sources) {
    if (!source.url.startsWith('https://')) issues.push(`${source.id} gebruikt geen veilige URL.`)
    try { new URL(source.url) } catch { issues.push(`${source.id} gebruikt een ongeldige URL.`) }
    if (!source.title || !source.publisher || !source.reviewedAt) issues.push(`${source.id} mist verplichte bronmetadata.`)
  }
  return issues
}
