import type { ServiceContent } from './public-content-model'
import { publicRoutes } from './public-routes'

const serviceEnhancements = {
  rie: {
    practiceExample: 'Een groeiend productiebedrijf voegt een nieuwe machine en avondploeg toe. De begeleider onderzoekt samen met medewerkers de nieuwe werkzaamheden, vergelijkt maatregelen met de praktijk en helpt risico’s, eigenaars en termijnen concreet in het plan van aanpak vast te leggen.',
    rieRelationship: 'Deze dienst richt zich rechtstreeks op de RI&E en het bijbehorende plan van aanpak. De deskundige helpt informatie ordenen en verdiepen; de organisatie blijft eigenaar van de werkelijke risico’s, gekozen maatregelen en periodieke actualisatie.',
    preparation: 'Verzamel vooraf de huidige RI&E, het plan van aanpak, een overzicht van werkzaamheden en locaties en relevante signalen van medewerkers. Noteer welke veranderingen sinds de vorige beoordeling hebben plaatsgevonden en welke maatregelen al zijn geprobeerd. Benoem ook waar onzekerheid zit: ontbreekt kennis over een risico, is de uitvoering vastgelopen of is onafhankelijke toetsing nodig? Met die informatie kan een deskundige sneller bepalen welke delen actualisatie, verdieping of toetsing vragen. Betrek werknemers en medezeggenschap tijdig, omdat zij zicht hebben op het dagelijkse werk en de uitvoerbaarheid van maatregelen.',
    additionalFaq: { question: 'Hoe vaak moet een RI&E worden bijgewerkt?', answer: 'Er is geen algemene vaste termijn. Actualiseer de RI&E wanneer veranderingen, incidenten of nieuwe inzichten gevolgen kunnen hebben voor de risico’s en maatregelen.' },
  },
  preventiemedewerker: {
    practiceExample: 'Bij een organisatie met meerdere vestigingen is onduidelijk wie acties uit de RI&E opvolgt. Een adviseur helpt de preventiemedewerker taken afbakenen, een overlegstructuur opzetten en signalen van medewerkers vertalen naar concrete verbeteracties.',
    rieRelationship: 'De preventiemedewerker werkt mee aan het opstellen en uitvoeren van de RI&E. Ondersteuning is daarom vooral waardevol wanneer de RI&E wel risico’s benoemt, maar eigenaarschap, dagelijkse opvolging of terugkoppeling naar medewerkers onvoldoende is georganiseerd.',
    preparation: 'Breng in kaart wie de preventiemedewerker is, hoeveel tijd beschikbaar is en welke taken al worden uitgevoerd. Leg daarnaast de RI&E, het plan van aanpak, afspraken met OR of PVT en terugkerende signalen uit de werkvloer klaar. Bespreek vooraf welke ondersteuning nodig is: kennisoverdracht, coaching, taakafbakening of hulp bij een concreet risico. Een duidelijke opdracht voorkomt dat externe ondersteuning de interne rol overneemt. Zorg dat werkgever, preventiemedewerker en medezeggenschap weten hoe adviezen worden besproken, wie besluiten neemt en hoe acties worden gevolgd.',
    additionalFaq: { question: 'Hoeveel tijd heeft een preventiemedewerker nodig?', answer: 'Dat hangt af van omvang, risico’s en taken. De beschikbare tijd moet voldoende zijn om de afgesproken preventietaken in de praktijk zorgvuldig uit te voeren.' },
  },
  bhv: {
    practiceExample: 'Een bedrijf heeft overdag voldoende BHV’ers, maar niet tijdens avonddiensten en vakanties. De adviseur toetst bezetting en noodscenario’s per tijdvak, bespreekt alarmering en middelen en organiseert een oefening om te zien of de afspraken daadwerkelijk werken.',
    rieRelationship: 'De RI&E levert de risico’s en scenario’s waarop de BHV-organisatie moet aansluiten. Veranderingen in locatie, werkzaamheden, bezetting of aanwezige personen kunnen daarom aanleiding zijn om zowel de RI&E als de BHV-inrichting opnieuw te beoordelen.',
    preparation: 'Maak per locatie en tijdvak inzichtelijk hoeveel medewerkers, bezoekers en minder zelfredzame personen aanwezig kunnen zijn. Verzamel plattegronden, noodprocedures, gegevens over alarmering en middelen en de uitkomsten van recente oefeningen. Beschrijf afwijkende situaties, zoals avondwerk, alleenwerk, evenementen of werkzaamheden met gevaarlijke stoffen. Kijk niet uitsluitend naar het aantal opgeleide BHV’ers, maar ook naar feitelijke beschikbaarheid, bereikbaarheid en samenwerking. Een adviseur kan dan gericht beoordelen welke scenario’s prioriteit hebben en waar opleiding, middelen, procedures of oefeningen moeten worden aangepast.',
    additionalFaq: { question: 'Hoe vaak moet een organisatie oefenen?', answer: 'De wet noemt geen universele frequentie. Oefen zo vaak als nodig om scenario’s, rollen en hulpmiddelen aantoonbaar werkbaar te houden en verbeterpunten te toetsen.' },
  },
  bedrijfsarts: {
    practiceExample: 'Meerdere medewerkers melden vergelijkbare klachten bij hetzelfde werkproces. De bedrijfsarts beoordeelt de relatie tussen werk en gezondheid binnen het medisch beroepsgeheim en adviseert de organisatie op groepsniveau over preventieve vervolgstappen, zonder diagnoses te delen.',
    rieRelationship: 'Signalen van de bedrijfsarts kunnen wijzen op arbeidsrisico’s die in de RI&E onvoldoende zijn herkend of beheerst. De organisatie verwerkt uitsluitend passende, niet-medische inzichten in de risicoanalyse en het plan van aanpak; individuele gezondheidsinformatie blijft vertrouwelijk.',
    preparation: 'Formuleer de vraag zonder om diagnoses of individuele medische gegevens te vragen. Beschrijf werkzaamheden, belasting, relevante risico’s uit de RI&E en patronen die op organisatieniveau zichtbaar zijn. Geef aan of het gaat om preventie, verzuimbegeleiding, PAGO, een mogelijk beroepsziektesignaal of advies over werkhervatting. Controleer ook welke afspraken in het basiscontract staan en hoe werknemers zelfstandig toegang krijgen. Een heldere afbakening helpt de bedrijfsarts onafhankelijk adviseren en maakt duidelijk wanneer daarnaast technische of organisatorische expertise nodig is.',
    additionalFaq: { question: 'Kan een werknemer zelf naar de bedrijfsarts?', answer: 'Ja. Werknemers moeten de bedrijfsarts preventief en zonder onnodige drempel kunnen raadplegen, ook wanneer zij nog niet zijn uitgevallen.' },
  },
  pmo: {
    practiceExample: 'Een logistieke organisatie wil een breed gezondheidsprogramma inkopen. Eerst wordt vanuit de RI&E bepaald welke blootstellingen, fysieke belasting en werktijden werkelijk relevant zijn. Daarna adviseert de bedrijfsarts welke onderzoeksopzet bij die risico’s en het preventiedoel past.',
    rieRelationship: 'De actuele RI&E is het inhoudelijke vertrekpunt voor arbeidsgezondheidskundig onderzoek. Zonder koppeling aan concrete arbeidsrisico’s bestaat het risico dat een algemeen gezondheidsprogramma relevante werkgerelateerde schade niet onderzoekt en daardoor het wettelijke kerndoel mist.',
    preparation: 'Begin met de actuele RI&E en laat de bedrijfsarts bepalen welke arbeidsrisico’s, groepen en onderzoeksfrequentie relevant zijn. Leg vast welk preventiedoel het onderzoek heeft, hoe deelname vrijwillig blijft en wie medische gegevens verwerkt. Bespreek vooraf welke geanonimiseerde groepsinformatie de organisatie kan ontvangen en welke maatregelen daarop kunnen volgen. Informeer werknemers begrijpelijk over doel, privacy en vervolg. Kies pas daarna een onderzoeksaanbod. Zo voorkomt u dat een brede leefstijlcheck wordt ingekocht die aantrekkelijk oogt, maar de werkelijke arbeidsrisico’s onvoldoende onderzoekt.',
    additionalFaq: { question: 'Wat gebeurt er met de uitkomsten van een PMO?', answer: 'Individuele medische uitkomsten blijven vertrouwelijk. De organisatie kan alleen verantwoorde, niet-herleidbare groepsinzichten gebruiken om preventieve maatregelen te verbeteren.' },
  },
  'hogere-veiligheidskundige': {
    practiceExample: 'Na een proceswijziging ontstaan nieuwe raakvlakken tussen productie, onderhoud en externe monteurs. De veiligheidskundige analyseert technische en organisatorische barrières, bespreekt afwijkende situaties met betrokkenen en helpt maatregelen prioriteren voordat het gewijzigde proces volledig wordt ingevoerd.',
    rieRelationship: 'Een hogere veiligheidskundige kan specialistische onderdelen van de RI&E verdiepen of toetsen wanneer risico’s complex zijn. De bevindingen horen herleidbaar terug te komen in de risico-inschatting, het plan van aanpak en de evaluatie van ingevoerde maatregelen.',
    preparation: 'Beschrijf het proces, de betrokken installaties, afwijkende werkzaamheden en de concrete beslissing waarvoor advies nodig is. Verzamel tekeningen, procedures, eerdere onderzoeken, incidentgegevens en relevante onderdelen van de RI&E. Benoem welke veranderingen gepland zijn en welke randvoorwaarden niet eenvoudig kunnen wijzigen. Betrek medewerkers, onderhoud, engineering en leiding waar hun kennis nodig is. Vraag de veiligheidskundige aannames, prioriteiten en resterende onzekerheden expliciet vast te leggen. Daardoor kan de organisatie maatregelen niet alleen kiezen, maar later ook controleren of de beoogde risicoreductie is bereikt.',
    additionalFaq: { question: 'Welke informatie moet in een veiligheidsadvies staan?', answer: 'Een bruikbaar advies beschrijft de vraag, feiten, aannames, risicoafweging, voorgestelde maatregelen, prioriteiten en hoe de werking van maatregelen wordt geëvalueerd.' },
  },
  arbeidshygienist: {
    practiceExample: 'Medewerkers ervaren irritatie tijdens een specifieke productiestap. De arbeidshygiënist brengt bronnen, stoffen, duur en bestaande beheersing in kaart en bepaalt of metingen nodig zijn. Het advies begint bij bronmaatregelen en beschrijft hoe de werking later wordt gecontroleerd.',
    rieRelationship: 'De blootstellingsbeoordeling verdiept de RI&E voor gezondheidsrisico’s die niet betrouwbaar met een algemene checklist zijn vast te stellen. Aannames, meetgegevens en beheersmaatregelen moeten daarom navolgbaar worden gekoppeld aan de betreffende werkzaamheden en blootstellingsmomenten.',
    preparation: 'Maak een overzicht van processen, gebruikte producten, hoeveelheden, taakduur, werkplekken en bestaande ventilatie of beschermingsmiddelen. Verzamel veiligheidsinformatiebladen, eerdere metingen, klachtenpatronen en relevante RI&E-onderdelen. Neem ook afwijkende werkzaamheden mee, zoals storingen, schoonmaak en onderhoud, omdat piekblootstelling daar kan ontstaan. Vraag niet direct om een meting zonder beoordelingsvraag. De arbeidshygiënist bepaalt eerst welke informatie ontbreekt en welke meetstrategie representatief is. Spreek af hoe resultaten worden uitgelegd, welke bronmaatregelen voorrang krijgen en wanneer herbeoordeling nodig is.',
    additionalFaq: { question: 'Wie moet bij een blootstellingsonderzoek worden betrokken?', answer: 'Betrek medewerkers die het werk uitvoeren, leiding, preventiemedewerker en technische deskundigen. Zij kennen variaties, storingen en bestaande maatregelen die in documenten vaak ontbreken.' },
  },
  incidentonderzoek: {
    practiceExample: 'Na een bijna-ongeval blijkt de directe handeling duidelijk, maar niet waarom meerdere beveiligingen tegelijk konden falen. Een onderzoeker verzamelt feiten en ervaringen, onderzoekt technische en organisatorische omstandigheden en helpt maatregelen kiezen die verder gaan dan extra instructie.',
    rieRelationship: 'Een incident of bijna-ongeval levert nieuwe informatie over risico’s en de werking van maatregelen. Relevante lessen moeten daarom worden gebruikt om de RI&E en het plan van aanpak te actualiseren, zonder het onderzoek te beperken tot schuld of individueel gedrag.',
    preparation: 'Zorg eerst voor hulpverlening, een veilige situatie en eventuele wettelijke melding. Bewaar daarna relevante feiten, zoals foto’s, instellingen, werkvergunningen, planning en verklaringen, zonder het werk van toezichthouders te hinderen. Formuleer een onderzoeksvraag die gericht is op leren en niet al één oorzaak veronderstelt. Bepaal wie onafhankelijk kan onderzoeken en welke betrokkenen gehoord moeten worden. Spreek af hoe bevindingen, onzekerheden en maatregelen worden vastgelegd. Een zorgvuldig begin verkleint de kans dat informatie verloren gaat of dat alleen de laatste menselijke handeling aandacht krijgt.',
    additionalFaq: { question: 'Wie kan een incidentonderzoek uitvoeren?', answer: 'Dat hangt af van ernst en complexiteit. Kies iemand met passende onderzoekservaring, inhoudelijke deskundigheid en voldoende onafhankelijkheid ten opzichte van het onderzochte proces.' },
  },
} as const

type ServiceSlug = keyof typeof serviceEnhancements

type ServiceInput = Omit<ServiceContent, 'type' | 'status' | 'validationStatus' | 'evidenceLevel' | 'lastReviewed' | 'metadata' | 'faq' | 'notDirectlyWhen' | 'process' | 'organizationResponsibility' | 'practiceExample' | 'rieRelationship' | 'preparation' | 'slug'> & {
  slug: ServiceSlug
  faq: readonly [{ question: string; answer: string }, { question: string; answer: string }]
}

function service(input: ServiceInput): ServiceContent {
  const { additionalFaq, ...enhancement } = serviceEnhancements[input.slug]
  return {
    ...input,
    ...enhancement,
    type: 'service', status: 'PUBLISHED', validationStatus: input.slug === 'rie' ? 'VALIDATED' : 'CONTEXT_DEPENDENT', evidenceLevel: 'AUTHORITATIVE', lastReviewed: '2026-07-24',
    metadata: { title: `${input.title} | WorkMatchr`, description: input.summary },
    notDirectlyWhen: ['als de hulpvraag nog niet duidelijk is; begin dan met de Advieswijzer;', 'als direct handelen bij acuut gevaar of een medisch noodgeval nodig is.'],
    process: ['Verhelder de aanleiding, werkzaamheden en gewenste uitkomst.', 'Bepaal welke informatie, locaties en betrokkenen nodig zijn.', 'Laat de deskundige onderzoek of advies uitvoeren en bevindingen uitleggen.', 'Vertaal de uitkomst naar eigenaarschap, maatregelen en een passende evaluatie.'],
    organizationResponsibility: 'De organisatie blijft verantwoordelijk voor veilige en gezonde arbeidsomstandigheden, voor besluiten over maatregelen en voor de uitvoering en evaluatie daarvan. Een deskundige ondersteunt, maar neemt die verantwoordelijkheid niet over.',
    faq: [...input.faq, additionalFaq].map((item, index) => ({ id: `${input.slug}-faq-${index + 1}`, ...item })),
  }
}

export const services = [
  service({ id: 'service:rie', slug: 'rie', title: 'Ondersteuning bij uw RI&E', href: publicRoutes.rieService, summary: 'Breng arbeidsrisico’s systematisch in kaart en vertaal bevindingen naar een bruikbaar plan van aanpak.', positioning: 'RI&E-ondersteuning helpt een organisatie haar werkzaamheden, risico’s en bestaande maatregelen gestructureerd te onderzoeken. De passende aanpak hangt af van omvang, branche en risicoprofiel.', problem: 'Ondersteuning kan nuttig zijn wanneer kennis, tijd of onafhankelijk onderzoek ontbreekt om de RI&E zorgvuldig uit te voeren of actualiseren.', appropriateWhen: ['bij een eerste RI&E of een grote verandering in werk of organisatie;', 'bij specialistische risico’s of twijfel over volledigheid;', 'wanneer toetsing of een erkend branche-instrument moet worden beoordeeld.'], audience: 'Een generalist kan het proces begeleiden; specialistische risico’s kunnen inzet vragen van een gecertificeerde kerndeskundige.', outcomes: ['een navolgbare inventarisatie van werkzaamheden en risico’s;', 'prioriteiten en concrete maatregelen voor het plan van aanpak;', 'duidelijkheid over ontbrekende informatie en eventuele specialistische verdieping.'], expertise: ['RI&E-deskundigheid;', 'hogere veiligheidskunde, arbeidshygiëne of arbeids- en organisatiekunde waar passend;', 'bedrijfsarts bij arbeidsgezondheidskundige vraagstukken.'], legalContext: 'Artikel 5 van de Arbowet vormt de basis voor de RI&E en het plan van aanpak. Of en hoe toetsing nodig is, hangt af van de concrete situatie.', sourceIds: ['arbowet-current', 'arbeidsinspectie-rie', 'rijksoverheid-arbowet'], searchTerms: ['risico inventarisatie', 'plan van aanpak', 'toetsing', 'arbeidsrisico'], faq: [{ question: 'Voert WorkMatchr zelf de RI&E uit?', answer: 'Nee. WorkMatchr helpt uw vraag verduidelijken en maakt professionele ondersteuning inzichtelijk.' }, { question: 'Is een standaardchecklist voldoende?', answer: 'Niet vanzelf. De RI&E moet aansluiten op de werkelijke werkzaamheden en risico’s van de organisatie.' }] }),
  service({ id: 'service:preventiemedewerker', slug: 'preventiemedewerker', title: 'Ondersteuning van de preventiemedewerker', href: publicRoutes.preventionOfficerService, summary: 'Versterk de interne preventierol met praktische begeleiding, kennis en een werkbare taakverdeling.', positioning: 'De preventiemedewerker is een interne wettelijke rol. Externe ondersteuning kan helpen bij inrichting, opleiding en uitvoering, maar vervangt de aangewezen preventiemedewerker niet.', problem: 'Ondersteuning is passend wanneer taken, positie of samenwerking rond preventie nog onvoldoende duidelijk of uitvoerbaar zijn.', appropriateWhen: ['bij het aanwijzen of herpositioneren van de preventiemedewerker;', 'bij het vertalen van de RI&E naar dagelijkse preventietaken;', 'bij behoefte aan coaching, kennisoverdracht of tijdelijke ondersteuning.'], audience: 'De interne preventiemedewerker, werkgever en medezeggenschap werken samen; een arbodeskundige kan gericht adviseren.', outcomes: ['een helder takenpakket en realistische beschikbare tijd;', 'betere aansluiting tussen RI&E, maatregelen en werkvloer;', 'duidelijkere samenwerking met bedrijfsarts, arbodienst en medezeggenschap.'], expertise: ['kennis van preventie en RI&E;', 'organisatieadvies en praktische implementatie;', 'specialistische arbo-expertise voor concrete risico’s.'], legalContext: 'Artikel 13 van de Arbowet beschrijft deskundige bijstand door werknemers. Benoeming, positie en taken vragen afstemming met de medezeggenschap waar die aanwezig is.', sourceIds: ['arbowet-current', 'arboportaal-preventiemedewerker', 'rijksoverheid-arbowet'], searchTerms: ['preventie', 'interne rol', 'arbobeleid', 'or pvt'], faq: [{ question: 'Kan een externe adviseur de preventiemedewerker vervangen?', answer: 'De wettelijke basis is interne deskundige bijstand. Externe ondersteuning kan aanvullen, maar niet zonder meer de interne rol vervangen.' }, { question: 'Mag de werkgever zelf preventiemedewerker zijn?', answer: 'Bij maximaal 25 werknemers kan dat onder voorwaarden. De concrete inrichting en medezeggenschap blijven relevant.' }] }),
  service({ id: 'service:bhv', slug: 'bhv', title: 'Ondersteuning bij bedrijfshulpverlening', href: publicRoutes.bhvService, summary: 'Richt bedrijfshulpverlening in op basis van uw risico’s, bezetting, locaties en mogelijke noodsituaties.', positioning: 'BHV is een organisatieverantwoordelijkheid. Advies, oefeningen en opleiding kunnen helpen om de benodigde hulpverlening passend en uitvoerbaar te organiseren.', problem: 'Ondersteuning is nuttig wanneer scenario’s, bezetting, taakverdeling of aansluiting op de RI&E onvoldoende duidelijk zijn.', appropriateWhen: ['bij nieuwe of gewijzigde locaties en werkzaamheden;', 'wanneer bezetting, ploegendienst of thuiswerken de beschikbaarheid beïnvloeden;', 'na oefeningen, incidenten of signalen dat procedures niet werken.'], audience: 'Een BHV-adviseur of veiligheidskundige kan de organisatie ondersteunen; medewerkers moeten hun toegewezen taken doeltreffend kunnen uitvoeren.', outcomes: ['risicogebaseerde scenario’s en een passende BHV-organisatie;', 'duidelijke alarmering, rollen en verbinding met externe hulpdiensten;', 'gerichte oefeningen en aantoonbare verbeterpunten.'], expertise: ['BHV-organisatie en noodscenario’s;', 'brandveiligheid en eerste hulp waar relevant;', 'veiligheidskundige analyse van werkzaamheden en bezetting.'], legalContext: 'Artikel 15 van de Arbowet verlangt doeltreffende bijstand bij eerste hulp, brandbestrijding, evacuatie en verbinding met hulpdiensten. De invulling volgt uit de RI&E.', sourceIds: ['arbowet-current', 'rijksoverheid-arbowet', 'arboportaal-arbobeleid'], searchTerms: ['bhv', 'bedrijfshulpverlening', 'noodplan', 'evacuatie', 'brand'], faq: [{ question: 'Hoeveel BHV’ers zijn nodig?', answer: 'De wet noemt geen vast aantal. De organisatie moet onder alle relevante omstandigheden doeltreffende bijstand kunnen bieden.' }, { question: 'Is alleen een BHV-cursus voldoende?', answer: 'Niet altijd. Ook risico’s, bezetting, middelen, alarmering, procedures en oefeningen moeten op elkaar aansluiten.' }] }),
  service({ id: 'service:bedrijfsarts', slug: 'bedrijfsarts', title: 'Ondersteuning door een bedrijfsarts', href: publicRoutes.occupationalPhysicianService, summary: 'Krijg onafhankelijk medisch advies over de relatie tussen werk, gezondheid, preventie en inzetbaarheid.', positioning: 'De bedrijfsarts is een medisch specialist op het gebied van arbeid en gezondheid en adviseert onafhankelijk. Medische gegevens vallen onder het beroepsgeheim.', problem: 'Inzet kan relevant zijn bij preventieve gezondheidsvragen, beroepsziekten, verzuimbegeleiding, werkhervatting en onderzoek naar werkgerelateerde risico’s.', appropriateWhen: ['bij vragen over gezondheid en werk, ook zonder verzuim;', 'voor wettelijke taken binnen het basiscontract;', 'wanneer medische duiding of preventief advies nodig is.'], audience: 'Alleen een bevoegd bedrijfsarts verricht voorbehouden arbeidsgezondheidskundige taken; samenwerking met andere arbodeskundigen kan nodig zijn.', outcomes: ['onafhankelijke medische duiding binnen de professionele grenzen;', 'advies over preventie, belastbaarheid en passende werkmaatregelen;', 'signalering van werkgerelateerde gezondheidsrisico’s.'], expertise: ['BIG-geregistreerde bedrijfsarts;', 'arbodienst of zelfstandig bedrijfsarts binnen passende contractafspraken;', 'andere kerndeskundigen voor niet-medische risico’s.'], legalContext: 'De Arbowet verlangt deskundige bijstand bij specifieke taken en toegang van werknemers tot de bedrijfsarts. De minimale afspraken horen in het basiscontract.', sourceIds: ['arbowet-current', 'arboportaal-bedrijfsarts', 'arboportaal-basiscontract'], searchTerms: ['werk en gezondheid', 'verzuim', 'preventief spreekuur', 'medisch advies'], faq: [{ question: 'Kan een werkgever medische informatie opvragen?', answer: 'De bedrijfsarts werkt onafhankelijk en heeft medisch beroepsgeheim. Werkgevers ontvangen geen diagnosegegevens.' }, { question: 'Is de bedrijfsarts alleen voor zieke werknemers?', answer: 'Nee. Werknemers moeten de bedrijfsarts ook preventief kunnen raadplegen over gezondheid in relatie tot werk.' }] }),
  service({ id: 'service:pmo', slug: 'pmo', title: 'Preventief medisch onderzoek (PMO)', href: publicRoutes.pmoService, summary: 'Onderzoek gezondheid in relatie tot werk, met de RI&E als basis en met respect voor vrijwilligheid en privacy.', positioning: 'Een PMO kan breder zijn dan het wettelijk bedoelde PAGO. Alleen wanneer het onderzoek de arbeidsrisico’s en het wettelijke kerndoel voldoende dekt, kan het invulling geven aan PAGO.', problem: 'Ondersteuning is relevant wanneer een organisatie werkgerelateerde gezondheidsschade vroeg wil signaleren en preventieve maatregelen wil verbeteren.', appropriateWhen: ['als de RI&E gezondheidsrisico’s aanwijst;', 'bij blootstelling, fysieke belasting, nachtwerk of psychosociale belasting;', 'wanneer bestaand onderzoek niet duidelijk aansluit op arbeidsrisico’s.'], audience: 'Een bedrijfsarts adviseert over inhoud en frequentie; andere deskundigen kunnen bijdragen aan risicoanalyse en interventies.', outcomes: ['een risicogerichte onderzoeksopzet;', 'geanonimiseerde groepsinzichten voor preventie waar verantwoord;', 'individueel advies binnen medische vertrouwelijkheid.'], expertise: ['bedrijfsarts voor arbeidsgezondheidskundige inhoud;', 'arbeidshygiënist of andere deskundige voor blootstellingscontext;', 'privacy- en medezeggenschapskennis bij inrichting.'], legalContext: 'Artikel 18 van de Arbowet verplicht de werkgever periodiek een onderzoek aan te bieden dat gericht is op risico’s van het werk. Deelname is in beginsel vrijwillig.', sourceIds: ['arbowet-current', 'arboportaal-pago', 'arboportaal-bedrijfsarts'], searchTerms: ['pmo', 'pago', 'gezondheidsonderzoek', 'preventief medisch'], faq: [{ question: 'Zijn PMO en PAGO hetzelfde?', answer: 'Niet automatisch. PAGO heeft een wettelijk, arbeidsrisicogericht kerndoel; PMO kan ook bredere gezondheidsthema’s bevatten.' }, { question: 'Moeten werknemers deelnemen?', answer: 'De werkgever moet PAGO aanbieden, maar werknemers zijn in beginsel niet verplicht deel te nemen.' }] }),
  service({ id: 'service:hogere-veiligheidskundige', slug: 'hogere-veiligheidskundige', title: 'Hogere veiligheidskundige', href: publicRoutes.safetyExpertService, summary: 'Laat complexe veiligheidsvraagstukken systematisch onderzoeken en vertalen naar beheersmaatregelen.', positioning: 'Een hogere veiligheidskundige ondersteunt bij complexe technische en organisatorische veiligheidsrisico’s en kan, mits passend gecertificeerd, kerndeskundige taken uitvoeren.', problem: 'Inzet kan passen wanneer risico’s meerdere processen, installaties, locaties of partijen raken en een diepgaande veiligheidskundige analyse nodig is.', appropriateWhen: ['bij complexe machine-, proces- of bouwveiligheidsvraagstukken;', 'bij toetsing of verdieping van specialistische RI&E-onderdelen;', 'na ernstige incidenten of bij ingrijpende veranderingen.'], audience: 'De benodigde certificering en ervaring hangen af van de taak, sector en vraag; niet iedere veiligheidsvraag vraagt hetzelfde deskundigheidsniveau.', outcomes: ['systematische analyse van technische en organisatorische oorzaken;', 'onderbouwde prioritering volgens de arbeidshygiënische strategie;', 'maatregelen die aansluiten op proces, mens en organisatie.'], expertise: ['hogere veiligheidskunde;', 'proces- of machineveiligheid waar relevant;', 'incidentanalyse en implementatiebegeleiding.'], legalContext: 'De Arbowet verplicht de werkgever risico’s te beheersen en bij specifieke taken passende kerndeskundigheid in te zetten. De RI&E bepaalt welke verdieping nodig is.', sourceIds: ['arbowet-current', 'arboportaal-arbobeleid', 'arbeidsinspectie-rie'], searchTerms: ['hvk', 'veiligheidskundige', 'machineveiligheid', 'procesveiligheid'], faq: [{ question: 'Is altijd een HVK nodig?', answer: 'Nee. De aard en complexiteit van de vraag bepalen welke deskundigheid passend is.' }, { question: 'Neemt een HVK de werkgeversverantwoordelijkheid over?', answer: 'Nee. De deskundige adviseert; de organisatie besluit en blijft verantwoordelijk voor uitvoering en borging.' }] }),
  service({ id: 'service:arbeidshygienist', slug: 'arbeidshygienist', title: 'Arbeidshygiënist', href: publicRoutes.occupationalHygienistService, summary: 'Onderzoek blootstelling aan stoffen, geluid, klimaat en andere omgevingsfactoren op het werk.', positioning: 'Een arbeidshygiënist herkent, beoordeelt en helpt beheersen welke omgevingsfactoren de gezondheid van werkenden kunnen beïnvloeden.', problem: 'Inzet is passend wanneer aard, hoogte of duur van blootstelling onvoldoende bekend is of specialistische metingen en beoordeling nodig zijn.', appropriateWhen: ['bij gevaarlijke stoffen, stof, dampen, biologische agentia of geluid;', 'bij klimaat-, ventilatie- of binnenmilieuvragen;', 'voor verdieping van de RI&E en toetsing van beheersmaatregelen.'], audience: 'Een arbeidshygiënist kan als kerndeskundige optreden wanneer de kwalificatie en taak daarvoor passend zijn; laboratoria of andere specialisten kunnen aanvullend nodig zijn.', outcomes: ['een onderbouwde blootstellingsbeoordeling;', 'advies volgens bronaanpak en collectieve maatregelen;', 'een meet- en beheersstrategie die herhaalbaar kan worden geëvalueerd.'], expertise: ['arbeidshygiëne en blootstellingsbeoordeling;', 'meetstrategie en interpretatie;', 'kennis van relevante stoffen en fysische factoren.'], legalContext: 'De Arbowet verlangt risicoaanpak bij de bron waar redelijkerwijs mogelijk. Nadere eisen kunnen uit het Arbobesluit volgen; de concrete stof of factor bepaalt de beoordeling.', sourceIds: ['arbowet-current', 'arboportaal-arbobeleid', 'arbeidsinspectie-rie'], searchTerms: ['arbeidshygienist', 'blootstelling', 'gevaarlijke stoffen', 'geluid', 'ventilatie'], faq: [{ question: 'Is meten altijd nodig?', answer: 'Nee. Eerst wordt bepaald welke informatie al beschikbaar is en of meten nodig is om een betrouwbare beoordeling te maken.' }, { question: 'Gaat arbeidshygiëne alleen over gevaarlijke stoffen?', answer: 'Nee. Ook onder meer geluid, klimaat, biologische agentia en andere omgevingsfactoren kunnen relevant zijn.' }] }),
  service({ id: 'service:incidentonderzoek', slug: 'incidentonderzoek', title: 'Incident- en ongevallenonderzoek', href: publicRoutes.incidentInvestigationService, summary: 'Onderzoek wat een incident mogelijk maakte en vertaal de lessen naar structurele verbetering.', positioning: 'Incidentonderzoek kijkt verder dan de directe fout en onderzoekt technische, organisatorische en menselijke omstandigheden. Het staat los van de vraag of een ongeval wettelijk meldingsplichtig is.', problem: 'Ondersteuning is relevant bij ernstige of herhaalde incidenten, bijna-ongevallen en situaties waarin oorzaken of verbetermaatregelen onvoldoende duidelijk zijn.', appropriateWhen: ['na een incident of bijna-ongeval met leerpotentieel;', 'bij terugkerende afwijkingen of onveilige situaties;', 'wanneer onafhankelijkheid of specialistische analysekracht nodig is.'], audience: 'Een ervaren incidentonderzoeker of veiligheidskundige kan het proces begeleiden; bij meldingsplichtige ongevallen gelden daarnaast instructies van de Arbeidsinspectie.', outcomes: ['een zorgvuldig feitenbeeld zonder voortijdige schuldtoewijzing;', 'inzicht in directe en onderliggende oorzaken;', 'concrete verbetermaatregelen en opvolging.'], expertise: ['incidentanalyse en interviewtechniek;', 'veiligheidskundige en organisatorische analyse;', 'kennis van meldings- en onderzoekscontext.'], legalContext: 'Er bestaat geen algemene plicht om ieder incident extern te laten onderzoeken. Meldingsplichtige arbeidsongevallen moeten wel direct bij de Nederlandse Arbeidsinspectie worden gemeld; registratie en medewerking kennen eigen regels.', sourceIds: ['arbowet-current', 'arbeidsinspectie-ongevallen'], searchTerms: ['incident', 'ongevalsonderzoek', 'bijna ongeval', 'root cause'], faq: [{ question: 'Is ieder incident meldingsplichtig?', answer: 'Nee. Voor melding gelden specifieke criteria. Bij twijfel adviseert de Arbeidsinspectie om te melden zodat zij de meldingsplicht kan beoordelen.' }, { question: 'Is onderzoek bedoeld om schuldigen aan te wijzen?', answer: 'Een goed leeronderzoek richt zich op feiten, omstandigheden en structurele verbetering, zonder juridische verantwoordelijkheden te negeren.' }] }),
] as const satisfies readonly ServiceContent[]

export function getServiceBySlug(slug: string): ServiceContent | undefined { return services.find((item) => item.slug === slug) }
export function getServiceById(id: string): ServiceContent | undefined { return services.find((item) => item.id === id) }
