import type { KnowledgeArticleContent } from '../public-content-model'
import { publicRoutes } from '../public-routes'

const articleEnhancements = {
  'moet-ik-een-rie-hebben': {
    relevantWhen: 'Deze vraag is relevant zodra mensen onder uw gezag werkzaamheden uitvoeren, ook wanneer niet iedereen een vast arbeidscontract heeft. Denk daarnaast opnieuw aan de RI&E bij verhuizing, groei, nieuwe machines, andere stoffen, gewijzigde werktijden of een ernstig incident.',
    practiceExample: 'Een ondernemer neemt voor het eerst twee medewerkers en een stagiair aan. Een algemene branchechecklist helpt bij de start, maar de ondernemer moet ook de eigen werkplek, taken, machines en bijzondere groepen beoordelen en concrete maatregelen in een plan van aanpak opnemen.',
    rieRelationship: 'De RI&E is hier het hoofdonderwerp: zij brengt de arbeidsrisico’s schriftelijk in kaart en koppelt die aan maatregelen. Een plan van aanpak is geen los document, maar onderdeel van dezelfde wettelijke en praktische verbetercyclus.',
    supportWhen: 'Ondersteuning is verstandig wanneer arbeidsrelaties onduidelijk zijn, meerdere locaties of specialistische risico’s spelen, een branche-instrument niet goed aansluit of twijfel bestaat over toetsing. Een deskundige kan de aanpak verdiepen; de werkgever blijft verantwoordelijk voor volledigheid en opvolging.',
    nextStep: 'Controleer eerst of binnen uw organisatie mensen onder gezag werken en leg vast welke werkzaamheden, locaties en groepen daarbij horen. Zoek vervolgens of voor uw branche een erkend RI&E-instrument beschikbaar is en beoordeel of dit werkelijk aansluit op uw situatie. Verzamel bestaande veiligheidsinformatie, incidenten, medewerkerssignalen en maatregelen. Plan daarna samen met werknemers of medezeggenschap hoe risico’s worden geïnventariseerd en wie acties opvolgt. Bij twijfel over toepasselijkheid, specialistische risico’s of toetsing is het verstandig de vraag vroeg aan een passende arbodeskundige voor te leggen.',
    additionalFaq: { question: 'Geldt de RI&E ook voor kleine werkgevers?', answer: 'Ja, zodra sprake is van arbeid onder gezag kan de verplichting gelden. De omvang beïnvloedt de aanpak, maar heft de verantwoordelijkheid niet automatisch op.' },
  },
  'wat-doet-een-preventiemedewerker': {
    relevantWhen: 'De rol is relevant voor iedere werkgever en wordt extra belangrijk wanneer de RI&E wordt opgesteld, werkzaamheden veranderen of maatregelen blijven liggen. Ook signalen van medewerkers, incidenten en overleg met OR of PVT vragen een herkenbaar intern aanspreekpunt.',
    practiceExample: 'In een kantoororganisatie staat werkdruk in de RI&E, maar acties blijven algemeen. De preventiemedewerker verzamelt signalen uit teams, bespreekt oorzaken met leiding en medezeggenschap en volgt of afgesproken maatregelen werkelijk worden uitgevoerd en geëvalueerd.',
    rieRelationship: 'Meewerken aan de RI&E en aan de uitvoering van het plan van aanpak behoort tot de kerntaken. De preventiemedewerker verbindt de formele risicoanalyse met dagelijkse ervaringen en helpt bewaken dat nieuwe of veranderde risico’s worden verwerkt.',
    supportWhen: 'Externe ondersteuning kan helpen bij taakafbakening, deskundigheidsontwikkeling of een complexe risicoanalyse. Laat ondersteuning de interne rol versterken en niet onzichtbaar vervangen; tijd, positie, toegang tot informatie en samenwerking moeten binnen de organisatie zijn geborgd.',
    nextStep: 'Controleer of een preventiemedewerker formeel is aangewezen en of taken, tijd en positie herkenbaar zijn vastgelegd. Bespreek met de medewerker welke acties uit de RI&E lopen, waar informatie ontbreekt en welke samenwerking met werkgever, bedrijfsarts en medezeggenschap nodig is. Maak een eenvoudige jaarplanning met terugkerende rondgangen, overleg en opvolging. Vraag werknemers hoe zij risico’s kunnen melden en hoe terugkoppeling plaatsvindt. Wanneer de rol vooral op papier bestaat, begin dan met taakafbakening en beschikbare tijd voordat u aanvullende opleidingen of externe projecten inkoopt.',
    additionalFaq: { question: 'Moet iedere organisatie een preventiemedewerker aanwijzen?', answer: 'Werkgevers moeten deskundige bijstand door werknemers organiseren. De precieze inrichting hangt af van omvang en situatie; bij maximaal 25 werknemers kan de werkgever onder voorwaarden zelf de rol vervullen.' },
  },
  'hoeveel-bhvers-heb-ik-nodig': {
    relevantWhen: 'Herbeoordeling is nodig bij een nieuwe locatie, andere bezetting, ploegendienst, thuiswerken, bezoekers, nachtwerk of gewijzigde noodscenario’s. Het gaat niet alleen om het aantal op papier, maar om feitelijke aanwezigheid en doeltreffend handelen wanneer iets gebeurt.',
    practiceExample: 'Een winkel heeft drie opgeleide BHV’ers, maar zij werken meestal tegelijk. Tijdens koopavonden is soms niemand aanwezig. Door per tijdvak en locatie te plannen, vervanging te regelen en ontruiming te oefenen ontstaat een realistischer bezetting dan met één algemeen aantal.',
    rieRelationship: 'De RI&E en de daaruit afgeleide noodscenario’s bepalen welke hulpverlening nodig kan zijn. Brand, letsel, gevaarlijke stoffen, verminderd zelfredzame bezoekers en bereikbaarheid van hulpdiensten kunnen allemaal invloed hebben op organisatie, middelen en oefeningen.',
    supportWhen: 'Een BHV-adviseur of veiligheidskundige is nuttig wanneer locaties, scenario’s of bezettingspatronen complex zijn, oefeningen terugkerende tekortkomingen laten zien of intern onvoldoende kennis bestaat om de organisatie risicogebaseerd te beoordelen.',
    nextStep: 'Maak per locatie en tijdvak een overzicht van aanwezigen, werkzaamheden en noodscenario’s. Controleer vervolgens of voldoende opgeleide mensen daadwerkelijk beschikbaar zijn bij ziekte, verlof, pauzes en afwijkende diensten. Loop alarmering, vluchtroutes, hulpmiddelen en contact met externe hulpdiensten praktisch na. Organiseer een oefening die past bij een realistisch scenario en registreer wat niet werkte. Gebruik de uitkomst om bezetting, instructies of middelen aan te passen. Neem daarbij bezoekers, contractors en medewerkers die hulp nodig hebben bij een evacuatie expliciet mee. Controleer bovendien of vervangers toegang hebben tot middelen en actuele contactinformatie. Een vast aantal is pas betekenisvol als duidelijk is onder welke omstandigheden die mensen doeltreffend moeten handelen.',
    additionalFaq: { question: 'Tellen ploegendienst en thuiswerken mee?', answer: 'Ja. De BHV-organisatie moet aansluiten op de feitelijke aanwezigheid per locatie en tijdvak, inclusief uitval, alleenwerk en wisselende bezetting. Leg deze beoordeling aantoonbaar vast.' },
  },
  'verschil-pmo-en-pago': {
    relevantWhen: 'Het onderscheid is relevant wanneer u gezondheidsonderzoek wilt inkopen, een bestaand PMO wilt vernieuwen of wilt controleren of het aanbod aansluit op de risico’s uit het werk. Een aantrekkelijk breed programma is niet automatisch hetzelfde als het wettelijk bedoelde PAGO.',
    practiceExample: 'Een bedrijf biedt een algemene leefstijlcheck aan, terwijl medewerkers dagelijks aan lawaai worden blootgesteld. Zonder gehoorgerichte en arbeidsrisicogebonden inhoud dekt het programma die werkelijke blootstelling mogelijk niet. De RI&E en het advies van de bedrijfsarts sturen daarom de onderzoeksopzet.',
    rieRelationship: 'De RI&E bepaalt welke arbeidsrisico’s in het PAGO aandacht vragen. Nieuwe blootstellingen, gezondheidskundige signalen of gewijzigde werkzaamheden kunnen aanleiding zijn om inhoud en frequentie opnieuw met de bedrijfsarts te beoordelen.',
    supportWhen: 'Vraag een bedrijfsarts om advies wanneer doel, inhoud, frequentie of privacy niet helder zijn. Een arbeidshygiënist kan aanvullende blootstellingsinformatie leveren. Leg vooraf vast wat de organisatie met geanonimiseerde groepsinzichten doet en welke medische gegevens buiten beeld blijven.',
    nextStep: 'Neem de actuele RI&E als startpunt en noteer welke arbeidsrisico’s mogelijk gezondheidsschade veroorzaken. Vraag de bedrijfsarts welk onderzoek daarbij past, voor welke groepen en met welke frequentie. Vergelijk dat advies met het voorgestelde PMO-programma: zijn de relevante blootstellingen werkelijk opgenomen, is deelname vrijwillig en blijft medische informatie vertrouwelijk? Leg ook vast hoe niet-herleidbare groepsuitkomsten tot preventieve acties kunnen leiden. Bepaal vooraf hoe werknemers worden geïnformeerd en bij wie zij met vragen terechtkunnen. Plan na afloop een evaluatie van deelname, bruikbaarheid en preventieve opvolging, zonder individuele uitslagen op te vragen. Koop pas daarna een onderzoek in. Zo blijft het doel arbeidsgerelateerde schade voorkomen in plaats van alleen algemene gezondheidsinformatie verzamelen.',
    additionalFaq: { question: 'Wie bepaalt de inhoud van een PAGO?', answer: 'De inhoud volgt uit de arbeidsrisico’s. De bedrijfsarts adviseert over passende onderzoeksonderdelen en frequentie; de werkgever organiseert het aanbod.' },
  },
  'wanneer-bedrijfsarts-inschakelen': {
    relevantWhen: 'De bedrijfsarts is relevant bij verzuim en re-integratie, maar ook bij preventieve vragen, mogelijke beroepsziekten, terugkerende gezondheidsklachten, PAGO en twijfel over de relatie tussen belasting en werk. Werknemers moeten bovendien preventief toegang kunnen krijgen.',
    practiceExample: 'In een team ontstaan vergelijkbare arm- en schouderklachten zonder langdurig verzuim. De bedrijfsarts bespreekt individuele gezondheid vertrouwelijk en kan op organisatieniveau adviseren om werkbelasting, hulpmiddelen en herstelmogelijkheden nader te onderzoeken.',
    rieRelationship: 'Niet-medische signalen uit de bedrijfsartspraktijk kunnen aanleiding zijn om risico’s of maatregelen in de RI&E opnieuw te bekijken. Diagnoses en individuele dossiers horen daar nooit in; de organisatie gebruikt alleen passende, niet-herleidbare informatie voor preventie.',
    supportWhen: 'Schakel de bedrijfsarts tijdig in bij medische duiding of wettelijke taken. Betrek voor technische, organisatorische of blootstellingsvragen zo nodig andere kerndeskundigen. Een duidelijke vraag voorkomt dat de bedrijfsarts wordt ingezet voor beslissingen die bij werkgever of behandelaar horen.',
    nextStep: 'Controleer of uw basiscontract de toegang tot de bedrijfsarts, preventief spreekuur, verzuimbegeleiding, PAGO en beroepsziektemelding duidelijk regelt. Maak de onafhankelijke contactmogelijkheid bekend bij werknemers. Formuleer organisatievragen in termen van werkzaamheden, belasting en preventie, zonder medische details op te vragen. Bij terugkerende signalen kunt u de bedrijfsarts vragen welke niet-herleidbare inzichten relevant zijn voor de RI&E. Spreek af wie adviezen op organisatieniveau ontvangt en hoe preventieve acties worden gevolgd. Zorg dat leidinggevenden weten welke vragen zij wel en niet aan werknemers mogen stellen. Bepaal daarna of technische of organisatorische verdieping door bijvoorbeeld een arbeidshygiënist of veiligheidskundige nodig is. Houd medische beoordeling en werkgeversbesluiten duidelijk van elkaar gescheiden.',
    additionalFaq: { question: 'Wie betaalt een bezoek aan de bedrijfsarts?', answer: 'De werkgever organiseert en bekostigt de wettelijk vereiste arbodienstverlening. Voor werknemers mag preventieve toegang geen onnodige financiële of organisatorische drempel hebben. De reden voor contact blijft vertrouwelijk.' },
  },
  'wat-is-psychosociale-arbeidsbelasting': {
    relevantWhen: 'PSA is relevant bij signalen van hoge werkdruk, uitval, conflicten, agressie, pesten, discriminatie, seksuele intimidatie of onduidelijke sociale normen. Ook reorganisaties, personeelstekorten en sterk emotioneel belastend werk kunnen de risico’s veranderen.',
    practiceExample: 'Een klantenserviceteam meldt stress en verbaal geweld. Alleen een weerbaarheidstraining pakt de oorzaken niet volledig aan. De organisatie onderzoekt ook targets, pauzes, bezetting, escalatiemogelijkheden, opvang na incidenten en de manier waarop leidinggevenden meldingen opvolgen.',
    rieRelationship: 'PSA hoort herkenbaar in de RI&E te worden beoordeeld, inclusief oorzaken, risicogroepen en bestaande maatregelen. Het plan van aanpak combineert waar mogelijk bronmaatregelen met duidelijke normen, meldroutes, opvang, voorlichting en periodieke evaluatie.',
    supportWhen: 'Ondersteuning is verstandig wanneer anonimiteit, sociale veiligheid of complexe organisatieoorzaken een intern onderzoek bemoeilijken. Een arbeids- en organisatiedeskundige, bedrijfsarts of andere passende professional kan helpen, afhankelijk van de vraag en zonder verantwoordelijkheden over te nemen.',
    nextStep: 'Combineer signalen uit gesprekken, verzuim, incidenten en medewerkeronderzoek zonder individuele meldingen herleidbaar te maken. Onderzoek vervolgens welke kenmerken van het werk de belasting veroorzaken: hoeveelheid, planning, regelruimte, leiderschap, omgangsvormen of emotionele eisen. Leg in de RI&E vast wie risico loopt en welke bronmaatregelen mogelijk zijn. Maak veilige meldroutes bekend en spreek af hoe opvolging en bescherming tegen benadeling worden geregeld. Betrek werknemers bij het beoordelen van oorzaken en uitvoerbaarheid, maar dwing niemand persoonlijke ervaringen openbaar te delen. Wijs een eigenaar en evaluatiemoment aan voor iedere maatregel. Toets na invoering of werkdruk, gedrag en sociale veiligheid werkelijk verbeteren; alleen een training of losse campagne is daarvoor meestal onvoldoende.',
    additionalFaq: { question: 'Kan een medewerkeronderzoek de PSA-beoordeling vervangen?', answer: 'Niet volledig. Een onderzoek kan signalen geven, maar de organisatie moet ook oorzaken, risicogroepen, bestaande maatregelen en concrete opvolging beoordelen. Herhaal de beoordeling na belangrijke veranderingen of incidenten.' },
  },
  'wanneer-arbeidsongeval-melden': {
    relevantWhen: 'Beoordeel dit onmiddellijk na een ongeval en opnieuw zodra later informatie ontstaat over ziekenhuisopname of blijvend letsel. De meldplicht kan ook gelden voor uitzendkrachten en andere personen die onder gezag van de organisatie werken.',
    practiceExample: 'Na een val lijkt het letsel eerst beperkt, maar later volgt een ziekenhuisopname voor behandeling. De werkgever meldt het ongeval zodra die opname bekend is, bewaart relevante feiten en voorkomt dat intern onderzoek de verplichte melding of hulpverlening vertraagt.',
    rieRelationship: 'Een ongeval toont mogelijk dat een risico, werkwijze of maatregel in de RI&E onvolledig of onvoldoende effectief is. Gebruik de feiten en onderzoeksuitkomsten daarom om de RI&E en het plan van aanpak bij te werken, naast de afzonderlijke meld- en registratieverplichtingen.',
    supportWhen: 'Neem bij twijfel contact op met de Nederlandse Arbeidsinspectie en meld volgens de officiële route. Juridische of veiligheidskundige ondersteuning kan verstandig zijn bij ernstige gebeurtenissen, complexe arbeidsrelaties of onderzoek, maar mag een directe melding nooit vertragen.',
    nextStep: 'Verleen direct hulp en voorkom nieuw gevaar. Controleer daarna of sprake is van overlijden, ziekenhuisopname of blijvend letsel en meld onmiddellijk via de officiële kanalen wanneer een criterium geldt. Wacht niet op een intern onderzoek of volledige zekerheid; bij twijfel kan de Arbeidsinspectie de meldingsplicht beoordelen. Leg feiten, betrokken arbeidsrelatie en later bekend geworden letsel zorgvuldig vast. Beperk wijzigingen aan de plaats van het ongeval wanneer onderzoek kan volgen. Start daarnaast een passende interne evaluatie en verwerk relevante lessen in de RI&E en het plan van aanpak.',
    additionalFaq: { question: 'Moet een ongeval met een uitzendkracht worden gemeld?', answer: 'Dat kan. De meldplicht ziet ook op personen die onder gezag werken. Stem verantwoordelijkheden snel af, maar laat onduidelijkheid een noodzakelijke melding niet vertragen.' },
  },
  'wat-doet-een-arbeidshygienist': {
    relevantWhen: 'Arbeidshygiënische expertise is relevant wanneer medewerkers worden blootgesteld aan stoffen, stof, dampen, geluid, biologische agentia, hitte, kou of een problematisch binnenklimaat en de aard, duur of hoogte van die blootstelling niet betrouwbaar bekend is.',
    practiceExample: 'Bij een schoonmaakproces ruiken medewerkers regelmatig oplosmiddelen. De arbeidshygiënist onderzoekt producten, hoeveelheden, ventilatie, taakduur en piekmomenten. Pas daarna wordt bepaald of metingen nodig zijn en welke bron- of collectieve maatregelen voorrang krijgen.',
    rieRelationship: 'De analyse verdiept de RI&E met een navolgbare blootstellingsbeoordeling. Zij maakt duidelijk welke aannames, meetgegevens, grenswaarden en beheersmaatregelen bij een taak horen en hoe de organisatie later controleert of de gekozen aanpak voldoende werkt.',
    supportWhen: 'Vraag ondersteuning wanneer interne informatie niet voldoende is, specialistische metingen nodig lijken of maatregelen technisch moeten worden beoordeeld. Een bedrijfsarts kan daarnaast nodig zijn voor medische vragen; die rollen zijn aanvullend en niet onderling uitwisselbaar.',
    nextStep: 'Maak een overzicht van taken, stoffen, apparatuur, duur en frequentie van mogelijke blootstelling. Verzamel veiligheidsinformatiebladen, eerdere meetrapporten, ventilatiegegevens en signalen uit de werkvloer. Kijk ook naar onderhoud, schoonmaak, storingen en piekmomenten. Beschrijf welke maatregelen al bestaan en of hun werking is gecontroleerd. Noteer welke groepen mogelijk extra kwetsbaar zijn en welke omstandigheden tussen seizoenen of diensten verschillen. Laat medewerkers aangeven waar de feitelijke uitvoering afwijkt van procedures. Met deze basis kan een arbeidshygiënist eerst een blootstellingsbeoordeling maken en bepalen of meten meerwaarde heeft. Vraag om een navolgbare onderbouwing en maatregelen volgens de bronaanpak, inclusief een moment waarop u controleert of de blootstelling daadwerkelijk voldoende is verminderd.',
    additionalFaq: { question: 'Wat is het verschil met een bedrijfsarts?', answer: 'De arbeidshygiënist beoordeelt blootstelling en beheersing in de werkomgeving. De bedrijfsarts beoordeelt medische en arbeidsgezondheidskundige vragen binnen het beroepsgeheim. Beide disciplines kunnen elkaar aanvullen. Meetonzekerheid blijft daarbij altijd expliciet zichtbaar.' },
  },
  'wanneer-incidentonderzoek-zinvol': {
    relevantWhen: 'Onderzoek is zinvol bij ernstige of herhaalde incidenten, bijna-ongevallen met grote mogelijke gevolgen en situaties waarin oorzaken of effectieve maatregelen niet duidelijk zijn. De gewenste diepgang hoort in verhouding te staan tot risico en leerpotentieel.',
    practiceExample: 'Een beveiliging wordt tijdelijk overbrugd om een storing op te lossen. In plaats van alleen de medewerker aan te spreken onderzoekt de organisatie ook storingsfrequentie, productiedruk, procedures, toezicht, ontwerpkeuzes en eerdere signalen. Daardoor worden structurelere maatregelen zichtbaar.',
    rieRelationship: 'Nieuwe feiten over gevaren, blootstelling en falende barrières horen terug te komen in de RI&E. Het plan van aanpak legt vervolgens vast welke technische, organisatorische en gedragsgerichte maatregelen worden ingevoerd, wie eigenaar is en hoe effect wordt gecontroleerd.',
    supportWhen: 'Een onafhankelijke onderzoeker of veiligheidskundige kan helpen wanneer belangen botsen, specialistische analysekracht ontbreekt of het incident meerdere processen en partijen raakt. Zorg dat onderzoek hulpverlening, wettelijke melding en instructies van toezichthouders niet doorkruist.',
    nextStep: 'Bepaal eerst of hulpverlening, veiligstelling of melding nodig is. Leg daarna snel feiten vast: de situatie, betrokken werkzaamheden, apparatuur, planning, procedures en ervaringen van betrokkenen. Kies de diepgang op basis van mogelijke ernst, herhaling en onzekerheid. Formuleer geen onderzoeksvraag die de oorzaak al bij één persoon legt. Onderzoek waarom technische en organisatorische barrières niet werkten en betrek mensen die het dagelijkse proces kennen. Vertaal conclusies naar concrete eigenaren en termijnen en controleer later of maatregelen daadwerkelijk het risico verminderen. Werk de RI&E bij wanneer nieuwe risico-informatie ontstaat.',
    additionalFaq: { question: 'Wat is het verschil tussen een feitenonderzoek en een schuldvraag?', answer: 'Een leergericht feitenonderzoek onderzoekt omstandigheden en barrières. Juridische verantwoordelijkheid kan apart relevant zijn, maar mag het verzamelen van bruikbare veiligheidslessen niet voortijdig vernauwen.' },
  },
} as const

type ArticleSlug = keyof typeof articleEnhancements

type ArticleInput = Omit<KnowledgeArticleContent, 'type' | 'status' | 'validationStatus' | 'evidenceLevel' | 'lastReviewed' | 'metadata' | 'faq' | 'relevantWhen' | 'practiceExample' | 'rieRelationship' | 'supportWhen' | 'nextStep' | 'slug'> & {
  slug: ArticleSlug
  faq: readonly [{ question: string; answer: string }, { question: string; answer: string }]
}
function article(input: ArticleInput): KnowledgeArticleContent {
  const { additionalFaq, ...enhancement } = articleEnhancements[input.slug]
  return { ...input, ...enhancement, type: 'knowledge', status: 'PUBLISHED', validationStatus: input.slug === 'moet-ik-een-rie-hebben' ? 'VALIDATED' : 'CONTEXT_DEPENDENT', evidenceLevel: 'AUTHORITATIVE', lastReviewed: '2026-07-24', metadata: { title: `${input.title} | WorkMatchr`, description: input.summary }, faq: [...input.faq, additionalFaq].map((item, index) => ({ id: `${input.slug}-faq-${index + 1}`, ...item })) }
}

export const knowledgeArticles = [
  article({ id: 'knowledge:rie-required', slug: 'moet-ik-een-rie-hebben', title: 'Moet ik een RI&E hebben?', href: publicRoutes.rieQuestion, summary: 'Heeft uw organisatie personeel, dan moet u als werkgever in beginsel een schriftelijke RI&E met plan van aanpak hebben.', shortAnswer: 'Heeft uw organisatie personeel, dan geldt in beginsel de RI&E-verplichting. Uw arbeidsrelaties, branche, personeelsomvang en gebruikte instrument bepalen hoe u de RI&E uitvoert en of toetsing nodig is.', context: ['De RI&E beschrijft de gevaren en risico’s van het werk, bestaande maatregelen en bijzondere groepen werknemers. Het plan van aanpak maakt er onderdeel van uit.', 'Onder personeel kunnen ook andere werkrelaties vallen dan werknemers met een vast contract. Laat twijfel over uw concrete situatie gericht beoordelen.'], practicalPoints: ['beschrijf de echte werkzaamheden, locaties en groepen;', 'gebruik geen algemene checklist als eindpunt;', 'maak maatregelen, termijnen en verantwoordelijken concreet;', 'actualiseer bij veranderingen, incidenten en nieuwe inzichten.'], legalContext: 'Artikel 5 van de Arbowet vormt de basis. Kleine werkgevers kunnen onder voorwaarden andere toetsingsregels gebruiken, maar zijn met personeel niet automatisch vrijgesteld van een RI&E.', sourceIds: ['arbowet-current', 'arbeidsinspectie-rie', 'rijksoverheid-arbowet'], searchTerms: ['rie nodig', 'personeel', 'risico inventarisatie', 'werkgever'], faq: [{ question: 'Heb ik zonder personeel een RI&E nodig?', answer: 'Volgens Rijksoverheid niet. Laat bij twijfel wel beoordelen of personen feitelijk onder uw gezag werken.' }, { question: 'Is de RI&E eenmalig?', answer: 'Nee. Wijzigingen, ervaringen en nieuwe inzichten kunnen actualisatie nodig maken.' }] }),
  article({ id: 'knowledge:preventiemedewerker', slug: 'wat-doet-een-preventiemedewerker', title: 'Wat doet een preventiemedewerker?', href: publicRoutes.preventionOfficerQuestion, summary: 'De preventiemedewerker helpt intern bij RI&E, advies en uitvoering van preventieve maatregelen.', shortAnswer: 'De preventiemedewerker is de interne schakel tussen risicoanalyse, advies en dagelijkse uitvoering. De rol vraagt voldoende deskundigheid, tijd en een herkenbare positie.', context: ['De wettelijke kerntaken zijn meewerken aan de RI&E, adviseren en samenwerken met medezeggenschap, en helpen bij uitvoering van maatregelen.', 'Een externe adviseur kan ondersteunen, maar de wettelijke inrichting gaat uit van interne deskundige bijstand.'], practicalPoints: ['leg taken, tijd, middelen en toegang tot informatie vast;', 'betrek de rol vroeg bij veranderingen en incidenten;', 'organiseer overleg met bedrijfsarts, arbodienst en medezeggenschap;', 'stem deskundigheid af op de risico’s.'], legalContext: 'Artikel 13 van de Arbowet regelt deskundige bijstand door werknemers. Bij maximaal 25 werknemers kan de werkgever onder voorwaarden zelf de rol vervullen.', sourceIds: ['arbowet-current', 'arboportaal-preventiemedewerker', 'rijksoverheid-arbowet'], searchTerms: ['preventiemedewerker taken', 'preventie', 'interne deskundige'], faq: [{ question: 'Moet iedere werkgever een preventiemedewerker hebben?', answer: 'Ja, ten minste één. De concrete invulling kan verschillen naar omvang en risico’s.' }, { question: 'Is een opleiding verplicht?', answer: 'Er is geen uniforme opleiding voor iedere situatie; de kennis en ervaring moeten passen bij de risico’s en taken.' }] }),
  article({ id: 'knowledge:bhv-capacity', slug: 'hoeveel-bhvers-heb-ik-nodig', title: 'Hoeveel BHV’ers heeft mijn organisatie nodig?', href: publicRoutes.bhvQuestion, summary: 'Er is geen vast wettelijk aantal; de BHV-organisatie moet onder alle relevante omstandigheden doeltreffend zijn.', shortAnswer: 'Bepaal het benodigde aantal en de spreiding vanuit risico’s, locaties, bezetting, werktijden en mogelijke uitval. Eén getal zonder die context is niet betrouwbaar.', context: ['De BHV moet eerste hulp, brandbestrijding, evacuatie en verbinding met hulpdiensten kunnen ondersteunen. Wat daarvoor nodig is verschilt per organisatie.', 'Vakantie, ziekte, ploegendienst, thuiswerk en meerdere locaties beïnvloeden de feitelijke beschikbaarheid.'], practicalPoints: ['gebruik de RI&E en noodscenario’s als uitgangspunt;', 'beoordeel aanwezigheid per locatie en tijdvak;', 'zorg voor middelen, alarmering, instructie en oefeningen;', 'test de organisatie en verbeter na oefeningen of incidenten.'], legalContext: 'Artikel 15 van de Arbowet verlangt doeltreffende bijstand maar noemt geen algemeen minimumaantal.', sourceIds: ['arbowet-current', 'rijksoverheid-arbowet', 'arboportaal-arbobeleid'], searchTerms: ['aantal bhv', 'bhvers', 'bedrijfshulpverlening'], faq: [{ question: 'Is één BHV’er genoeg?', answer: 'Dat kan niet zonder context worden bepaald. Afwezigheid, locaties en scenario’s moeten worden meegenomen.' }, { question: 'Moet iedere BHV’er een certificaat hebben?', answer: 'De wet stelt geen uniforme diplomaplicht, maar de taken moeten wel doeltreffend kunnen worden uitgevoerd.' }] }),
  article({ id: 'knowledge:pmo-pago', slug: 'verschil-pmo-en-pago', title: 'Wat is het verschil tussen PMO en PAGO?', href: publicRoutes.pmoPagoQuestion, summary: 'PAGO heeft een wettelijk arbeidsrisicogericht kerndoel; PMO kan ook bredere gezondheidsthema’s omvatten.', shortAnswer: 'Een PAGO richt zich op het vroeg signaleren en voorkomen van gezondheidsschade door risico’s in het werk. Een PMO kan breder zijn. Niet ieder PMO voldoet daardoor automatisch aan de PAGO-verplichting.', context: ['De RI&E vormt de basis voor de inhoud van PAGO. De bedrijfsarts adviseert over inhoud en frequentie.', 'Leefstijl- of inzetbaarheidsonderzoek kan waardevol zijn, maar vervangt het arbeidsrisicogerichte kerndoel niet zonder meer.'], practicalPoints: ['begin bij actuele arbeidsrisico’s;', 'maak doelen en vrijwilligheid duidelijk;', 'borg medische privacy en onafhankelijke uitvoering;', 'gebruik groepsuitkomsten zorgvuldig voor preventie.'], legalContext: 'Artikel 18 van de Arbowet verplicht werkgevers PAGO periodiek aan te bieden. Werknemers zijn in beginsel vrij om deel te nemen.', sourceIds: ['arbowet-current', 'arboportaal-pago', 'arboportaal-bedrijfsarts'], searchTerms: ['pmo pago verschil', 'gezondheidsonderzoek', 'preventief medisch'], faq: [{ question: 'Kan PMO aan PAGO voldoen?', answer: 'Ja, wanneer het ten minste het arbeidsrisicogerichte wettelijke doel en de relevante risico’s dekt.' }, { question: 'Mag de werkgever individuele uitslagen zien?', answer: 'Medische informatie is vertrouwelijk. Alleen verantwoorde, niet-herleidbare groepsinformatie kan voor preventie worden gebruikt.' }] }),
  article({ id: 'knowledge:occupational-physician', slug: 'wanneer-bedrijfsarts-inschakelen', title: 'Wanneer moet ik een bedrijfsarts inschakelen?', href: publicRoutes.occupationalPhysicianQuestion, summary: 'De bedrijfsarts is relevant bij preventie, gezondheid en werk, verzuim, re-integratie en wettelijke arbodienstverlening.', shortAnswer: 'Schakel de bedrijfsarts niet alleen bij verzuim in. Ook preventieve vragen, gezondheidssignalen, PAGO en advies over werkgerelateerde risico’s kunnen bedrijfsartsdeskundigheid vragen.', context: ['De bedrijfsarts adviseert onafhankelijk en bewaakt medisch beroepsgeheim. De werkgever krijgt geen diagnose.', 'Werknemers moeten de bedrijfsarts zonder onnodige drempel preventief kunnen raadplegen.'], practicalPoints: ['regel toegang en wettelijke taken in het basiscontract;', 'maak de preventieve contactroute bekend;', 'vraag advies op organisatieniveau zonder medische privacy te doorbreken;', 'betrek andere arbodeskundigen bij niet-medische risicovragen.'], legalContext: 'Artikel 14 van de Arbowet regelt deskundige bijstand. Het basiscontract bevat minimumeisen rond toegang, wettelijke taken en professionele onafhankelijkheid.', sourceIds: ['arbowet-current', 'arboportaal-bedrijfsarts', 'arboportaal-basiscontract'], searchTerms: ['bedrijfsarts inschakelen', 'verzuim', 'preventief spreekuur'], faq: [{ question: 'Is de bedrijfsarts hetzelfde als de huisarts?', answer: 'Nee. De bedrijfsarts is gespecialiseerd in de relatie tussen werk en gezondheid.' }, { question: 'Mag de werkgever vragen wat iemand mankeert?', answer: 'De werkgever mag geen diagnose opvragen; de bedrijfsarts adviseert binnen medische vertrouwelijkheid over werkmogelijkheden.' }] }),
  article({ id: 'knowledge:psa', slug: 'wat-is-psychosociale-arbeidsbelasting', title: 'Wat valt onder psychosociale arbeidsbelasting?', href: publicRoutes.psaQuestion, summary: 'PSA omvat onder meer werkdruk, agressie, geweld, pesten, discriminatie en seksuele intimidatie die stress kunnen veroorzaken.', shortAnswer: 'Psychosociale arbeidsbelasting gaat over factoren in de werksituatie die stress veroorzaken. De aanpak vraagt zowel preventie bij de bron als veilige melding en ondersteuning.', context: ['Werkdruk kan ontstaan door hoeveelheid werk, complexiteit, onduidelijke prioriteiten, beperkte regelruimte of onvoldoende herstel.', 'Ongewenst gedrag vraagt duidelijke normen en opvolging, maar ook onderzoek naar organisatie, leiderschap en sociale veiligheid.'], practicalPoints: ['neem PSA expliciet op in de RI&E;', 'onderzoek oorzaken en groepen zonder individuele signalen te negeren;', 'kies bron- en organisatorische maatregelen;', 'zorg voor melding, opvang, voorlichting en evaluatie.'], legalContext: 'De Arbowet verlangt beleid om psychosociale arbeidsbelasting te voorkomen of beperken. Nadere uitwerking staat in het Arbobesluit.', sourceIds: ['arbowet-current', 'arboportaal-arbobeleid', 'arbeidsinspectie-sectoren'], searchTerms: ['psa', 'werkdruk', 'pesten', 'agressie', 'sociale veiligheid'], faq: [{ question: 'Is werkstress altijd PSA?', answer: 'Stress kan meerdere oorzaken hebben. Voor PSA gaat het om relevante factoren in de arbeidssituatie.' }, { question: 'Is een vertrouwenspersoon genoeg?', answer: 'Een vertrouwenspersoon kan helpen, maar vervangt geen risicoanalyse en preventief organisatiebeleid.' }] }),
  article({ id: 'knowledge:accident-reporting', slug: 'wanneer-arbeidsongeval-melden', title: 'Wanneer moet een arbeidsongeval worden gemeld?', href: publicRoutes.accidentQuestion, summary: 'Meld een arbeidsongeval direct bij overlijden, ziekenhuisopname of blijvend letsel.', shortAnswer: 'De werkgever meldt direct wanneer het slachtoffer overlijdt, in een ziekenhuis wordt opgenomen of blijvend letsel heeft. Blijkt dit later, dan geldt de melding alsnog zodra het bekend is.', context: ['De meldingsplicht kan ook gelden voor personen die onder gezag werken, zoals uitzendkrachten of ingehuurde krachten.', 'Bij twijfel adviseert de Nederlandse Arbeidsinspectie om te melden; zij beoordeelt of het ongeval meldingsplichtig is.'], practicalPoints: ['verleen hulp en voorkom verder gevaar;', 'meld direct via de officiële kanalen;', 'bewaar de situatie en feiten waar dat veilig en nodig is;', 'registreer, werk mee aan onderzoek en vertaal lessen naar maatregelen.'], legalContext: 'Artikel 9 van de Arbowet regelt melding en registratie. De Nederlandse Arbeidsinspectie geeft actuele uitleg over criteria en werkwijze.', sourceIds: ['arbowet-current', 'arbeidsinspectie-ongevallen'], searchTerms: ['ongeval melden', 'ziekenhuis', 'blijvend letsel', 'arbeidsinspectie'], faq: [{ question: 'Telt een dagopname als ziekenhuisopname?', answer: 'De Arbeidsinspectie noemt ook een dagopname voor een ingreep of behandeling als relevante ziekenhuisopname.' }, { question: 'Wat als blijvend letsel later blijkt?', answer: 'Dan moet het ongeval alsnog direct worden gemeld zodra dit bekend is.' }] }),
  article({ id: 'knowledge:occupational-hygienist', slug: 'wat-doet-een-arbeidshygienist', title: 'Wat doet een arbeidshygiënist?', href: publicRoutes.occupationalHygienistQuestion, summary: 'Een arbeidshygiënist beoordeelt omgevingsfactoren en blootstelling die de gezondheid op het werk kunnen beïnvloeden.', shortAnswer: 'De arbeidshygiënist herkent, beoordeelt en helpt beheersen van blootstelling aan bijvoorbeeld stoffen, geluid, biologische agentia en binnenklimaat.', context: ['De deskundige begint met werkzaamheden, bronnen, duur en bestaande maatregelen en bepaalt daarna of aanvullende metingen nodig zijn.', 'Maatregelen volgen bij voorkeur de bronaanpak: eerst voorkomen of beperken aan de bron, daarna collectieve en pas later individuele bescherming.'], practicalPoints: ['beschrijf processen en blootstellingsmomenten;', 'verzamel veiligheidsinformatie en bestaande meetgegevens;', 'beoordeel representatieve én afwijkende situaties;', 'leg meetstrategie, aannames en opvolging navolgbaar vast.'], legalContext: 'De Arbowet verlangt bronaanpak en passende deskundige bijstand. Specifieke grenswaarden en voorschriften kunnen uit het Arbobesluit volgen.', sourceIds: ['arbowet-current', 'arboportaal-arbobeleid', 'arbeidsinspectie-rie'], searchTerms: ['arbeidshygienist', 'blootstelling', 'stoffen', 'geluid', 'binnenklimaat'], faq: [{ question: 'Doet een arbeidshygiënist altijd metingen?', answer: 'Nee. Meten is zinvol wanneer bestaande informatie onvoldoende is voor een betrouwbare beoordeling.' }, { question: 'Is een arbeidshygiënist een arts?', answer: 'Nee. Arbeidshygiëne richt zich op blootstelling en beheersing; medische beoordeling hoort bij een bedrijfsarts.' }] }),
  article({ id: 'knowledge:incident-investigation', slug: 'wanneer-incidentonderzoek-zinvol', title: 'Wanneer is incidentonderzoek zinvol?', href: publicRoutes.incidentInvestigationQuestion, summary: 'Onderzoek incidenten wanneer de lessen nodig zijn om herhaling te voorkomen en de veiligheidsaanpak te verbeteren.', shortAnswer: 'Onderzoek is vooral zinvol als feiten, oorzaken of verbetermaatregelen niet vanzelf duidelijk zijn, bij ernstige of herhaalde incidenten en bij bijna-ongevallen met groot potentieel.', context: ['Een goed onderzoek kijkt naar technische, organisatorische en menselijke omstandigheden en vermijdt een te vroege conclusie dat één fout alles verklaart.', 'Een intern leeronderzoek staat los van de wettelijke meldingsplicht en eventuele instructies van toezichthouders.'], practicalPoints: ['maak de situatie eerst veilig en borg noodzakelijke melding;', 'verzamel feiten tijdig en zorgvuldig;', 'betrek mensen zonder schuld al vast te stellen;', 'formuleer maatregelen op bron, systeem en uitvoering en volg ze op.'], legalContext: 'Er is geen algemene plicht om ieder incident extern te laten onderzoeken. Voor ernstige arbeidsongevallen gelden wel meld-, registratie- en medewerkingsplichten.', sourceIds: ['arbowet-current', 'arbeidsinspectie-ongevallen'], searchTerms: ['incidentonderzoek', 'bijna ongeval', 'oorzaakanalyse', 'leren'], faq: [{ question: 'Moet ieder bijna-ongeval worden onderzocht?', answer: 'Niet op dezelfde diepte. Ernstpotentieel, herhaling en onzekerheid bepalen welke analyse proportioneel is.' }, { question: 'Kan onderzoek wachten tot later?', answer: 'Feiten en herinneringen kunnen snel verloren gaan. Start daarom tijdig, zonder hulpverlening of wettelijke processen te hinderen.' }] }),
] as const satisfies readonly KnowledgeArticleContent[]

export function getKnowledgeArticleBySlug(slug: string): KnowledgeArticleContent | undefined { return knowledgeArticles.find((item) => item.slug === slug) }
