import type { KnowledgeArticleContent } from '../public-content-model'
import { publicRoutes } from '../public-routes'

const articleEnhancements = {
  'moet-ik-een-rie-hebben': {
    relevantWhen: 'Deze vraag is relevant zodra mensen onder uw gezag werkzaamheden uitvoeren, ook wanneer niet iedereen een vast arbeidscontract heeft. Denk daarnaast opnieuw aan de RI&E bij verhuizing, groei, nieuwe machines, andere stoffen, gewijzigde werktijden of een ernstig incident.',
    practiceExample: 'Een ondernemer neemt voor het eerst twee medewerkers en een stagiair aan. Een algemene branchechecklist helpt bij de start, maar de ondernemer moet ook de eigen werkplek, taken, machines en bijzondere groepen beoordelen en concrete maatregelen in een plan van aanpak opnemen.',
    rieRelationship: 'De RI&E is hier het hoofdonderwerp: zij brengt de arbeidsrisico’s schriftelijk in kaart en koppelt die aan maatregelen. Een plan van aanpak is geen los document, maar onderdeel van dezelfde wettelijke en praktische verbetercyclus.',
    supportWhen: 'Ondersteuning is verstandig wanneer arbeidsrelaties onduidelijk zijn, meerdere locaties of specialistische risico’s spelen, een branche-instrument niet goed aansluit of twijfel bestaat over toetsing. Een deskundige kan de aanpak verdiepen; de werkgever blijft verantwoordelijk voor volledigheid en opvolging.',
    nextStep: 'Controleer eerst of binnen uw organisatie mensen onder gezag werken en leg vast welke werkzaamheden, locaties en groepen daarbij horen. Zoek vervolgens of voor uw branche een erkend RI&E-instrument beschikbaar is en beoordeel of dit werkelijk aansluit op uw situatie. Verzamel bestaande veiligheidsinformatie, incidenten, medewerkerssignalen en maatregelen. Plan daarna samen met werknemers of medezeggenschap hoe risico’s worden geïnventariseerd en wie acties opvolgt. Bij twijfel over toepasselijkheid, specialistische risico’s of toetsing is het verstandig de vraag vroeg aan een passende arbodeskundige voor te leggen.',
    additionalFaq: { question: 'Geldt de RI&E ook voor kleine werkgevers?', answer: 'Ja, zodra sprake is van arbeid onder gezag kan de verplichting gelden. De omvang beïnvloedt de aanpak, maar heft de verantwoordelijkheid niet automatisch op.' },
  },
  'wat-doet-een-preventiemedewerker': {
    relevantWhen: 'Iedere werkgever met werknemers moet ten minste één preventiemedewerker aanwijzen. Betrokkenheid is extra relevant wanneer de RI&E wordt opgesteld, werkzaamheden veranderen, incidenten plaatsvinden of maatregelen blijven liggen.',
    practiceExample: 'In een kantoororganisatie staat werkdruk in de RI&E, maar acties blijven algemeen. De preventiemedewerker verzamelt signalen uit teams, bespreekt deze met leiding en medezeggenschap en volgt of afgesproken maatregelen worden uitgevoerd en geëvalueerd.',
    rieRelationship: 'Meewerken aan de RI&E en aan de uitvoering van het plan van aanpak behoort tot de kerntaken. De preventiemedewerker verbindt de formele risicoanalyse met dagelijkse ervaringen en helpt bewaken dat nieuwe of veranderde risico’s worden verwerkt.',
    supportWhen: 'Externe ondersteuning kan nodig zijn bij specialistische of complexe risico’s of onvoldoende interne kennis. Deze ondersteuning versterkt de interne rol en vervangt niet automatisch de verplichting om intern een preventiemedewerker aan te wijzen.',
    nextStep: 'Controleer of een preventiemedewerker formeel is aangewezen en of taken, tijd en positie herkenbaar zijn vastgelegd. Bespreek met de medewerker welke acties uit de RI&E lopen, waar informatie ontbreekt en welke samenwerking met werkgever, bedrijfsarts en medezeggenschap nodig is. Maak een eenvoudige jaarplanning met terugkerende rondgangen, overleg en opvolging. Vraag werknemers hoe zij risico’s kunnen melden en hoe terugkoppeling plaatsvindt. Wanneer de rol vooral op papier bestaat, begin dan met taakafbakening en beschikbare tijd voordat u aanvullende opleidingen of externe projecten inkoopt.',
    additionalFaq: { question: 'Kan een externe adviseur de preventiemedewerker vervangen?', answer: 'Niet automatisch. De Arbowet gaat uit van deskundige bijstand door één of meer werknemers. Externe deskundigheid kan nodig zijn wanneer de interne kennis onvoldoende is, maar ondersteunt dan de wettelijke interne rol.' },
  },
  'hoeveel-bhvers-heb-ik-nodig': {
    relevantWhen: 'Herbeoordeling is nodig bij een nieuwe locatie, andere bezetting, ploegendienst, thuiswerken, bezoekers, nachtwerk of gewijzigde noodscenario’s. Het gaat niet alleen om het aantal op papier, maar om feitelijke aanwezigheid en doeltreffend handelen wanneer iets gebeurt.',
    practiceExample: 'Een winkel heeft drie opgeleide BHV’ers, maar zij werken meestal tegelijk. Tijdens koopavonden is soms niemand aanwezig. Door per tijdvak en locatie te plannen, vervanging te regelen en ontruiming te oefenen ontstaat een realistischer bezetting dan met één algemeen aantal.',
    rieRelationship: 'De RI&E en de daaruit afgeleide noodscenario’s bepalen welke hulpverlening nodig kan zijn. Brand, letsel, gevaarlijke stoffen, verminderd zelfredzame bezoekers en bereikbaarheid van hulpdiensten kunnen allemaal invloed hebben op organisatie, middelen en oefeningen.',
    supportWhen: 'Een BHV-adviseur of veiligheidskundige is nuttig wanneer locaties, scenario’s of bezettingspatronen complex zijn, oefeningen terugkerende tekortkomingen laten zien of intern onvoldoende kennis bestaat om de organisatie risicogebaseerd te beoordelen.',
    nextStep: 'Maak per locatie en tijdvak een overzicht van aanwezigen, werkzaamheden en noodscenario’s. Controleer vervolgens of voldoende opgeleide mensen daadwerkelijk beschikbaar zijn bij ziekte, verlof, pauzes en afwijkende diensten. Loop alarmering, vluchtroutes, hulpmiddelen en contact met externe hulpdiensten praktisch na. Organiseer een oefening die past bij een realistisch scenario en registreer wat niet werkte. Gebruik de uitkomst om bezetting, instructies of middelen aan te passen. Neem daarbij bezoekers, contractors en medewerkers die hulp nodig hebben bij een evacuatie expliciet mee. Controleer bovendien of vervangers toegang hebben tot middelen en actuele contactinformatie. Een vast aantal is pas betekenisvol als duidelijk is onder welke omstandigheden die mensen doeltreffend moeten handelen.',
    additionalFaq: { question: 'Tellen ploegendienst en thuiswerken mee?', answer: 'Ja. De BHV-organisatie moet aansluiten op de feitelijke aanwezigheid per locatie en tijdvak, inclusief uitval, alleenwerk en wisselende bezetting. Leg deze beoordeling aantoonbaar vast.' },
  },
  'verschil-pmo-en-pago': {
    relevantWhen: 'Het onderscheid is relevant wanneer u gezondheidsonderzoek wilt inkopen, een bestaand PMO wilt vernieuwen of wilt controleren of het aanbod aansluit op de risico’s uit het werk. Een aantrekkelijk breed programma is niet automatisch hetzelfde als het wettelijk bedoelde PAGO.',
    practiceExample: 'Een bedrijf biedt een algemene leefstijlcheck aan, terwijl medewerkers dagelijks aan lawaai worden blootgesteld. Zonder gehoorgerichte en arbeidsrisicogebonden inhoud dekt het programma die werkelijke blootstelling mogelijk niet. De RI&E en het advies van de bedrijfsarts sturen daarom de onderzoeksopzet.',
    rieRelationship: 'De RI&E bepaalt welke arbeidsrisico’s in het PAGO aandacht vragen. Nieuwe blootstellingen, gezondheidskundige signalen of gewijzigde werkzaamheden kunnen aanleiding zijn om inhoud en frequentie opnieuw met de bedrijfsarts te beoordelen.',
    supportWhen: 'Vraag een bedrijfsarts om advies wanneer doel, inhoud, frequentie of privacy niet helder zijn. Een arbeidshygiënist kan aanvullende blootstellingsinformatie leveren. Leg vooraf vast wat de organisatie met geanonimiseerde groepsinzichten doet en welke medische gegevens buiten beeld blijven.',
    nextStep: 'Neem de actuele RI&E als startpunt en noteer welke arbeidsrisico’s mogelijk gezondheidsschade veroorzaken. Vraag de bedrijfsarts welk onderzoek daarbij past, voor welke groepen en met welke frequentie. Vergelijk dat advies met het voorgestelde PMO-programma: zijn de relevante blootstellingen werkelijk opgenomen, is deelname vrijwillig en blijft medische informatie vertrouwelijk? Leg ook vast hoe niet-herleidbare groepsuitkomsten tot preventieve acties kunnen leiden. Bepaal vooraf hoe werknemers worden geïnformeerd en bij wie zij met vragen terechtkunnen. Plan na afloop een evaluatie van deelname, bruikbaarheid en preventieve opvolging, zonder individuele uitslagen op te vragen. Koop pas daarna een onderzoek in. Zo blijft het doel arbeidsgerelateerde schade voorkomen in plaats van alleen algemene gezondheidsinformatie verzamelen.',
    additionalFaq: { question: 'Wie bepaalt de inhoud van een PAGO?', answer: 'De inhoud volgt uit de arbeidsrisico’s. De bedrijfsarts adviseert over passende onderzoeksonderdelen en frequentie; de werkgever organiseert het aanbod.' },
  },
  'wanneer-bedrijfsarts-inschakelen': {
    shortAnswer: 'De bedrijfsarts is niet alleen relevant bij ziekteverzuim. Ook preventieve vragen, de relatie tussen gezondheid en werk, re-integratie, PAGO en het signaleren van mogelijke beroepsziekten kunnen bedrijfsartsdeskundigheid vragen.',
    relevantWhen: 'De bedrijfsarts ondersteunt bij verzuim en re-integratie, maar ook wanneer werknemers preventief willen overleggen over hun gezondheid in relatie tot werk, bij werkgerelateerde klachten, een PAGO of signalen die mogelijk op een beroepsziekte wijzen.',
    practiceExample: 'In een team ontstaan vergelijkbare arm- en schouderklachten zonder langdurig verzuim. De bedrijfsarts beoordeelt de gezondheid van iedere werknemer vertrouwelijk. De werkgever kan vervolgens op basis van niet-herleidbare signalen onderzoeken of werkbelasting, hulpmiddelen of herstelmogelijkheden aandacht vragen.',
    context: [
      'De werkgever organiseert de wettelijke arbodienstverlening en zorgt dat werknemers de bedrijfsarts rechtstreeks kunnen bezoeken zonder voorafgaande toestemming, ook als zij nog niet ziekgemeld zijn of klachten hebben. De werknemer kan werk en gezondheid bespreken; de bedrijfsarts voert die taak onafhankelijk uit.',
      'De bedrijfsarts is een arts die zich richt op gezondheid in relatie tot werk. De behandelend arts richt zich op medische behandeling. De werkgever beslist over de inrichting van werk en organisatorische maatregelen. Andere arbodeskundigen kunnen specialistische, niet-medische risico’s beoordelen; die rollen vullen elkaar aan en vormen geen vaste verplichte route. De werkgever organiseert en bekostigt de wettelijk vereiste arbodienstverlening; preventieve toegang hoort geen onnodige financiële of organisatorische drempel op te werpen.',
      'Medische gegevens en privé-informatie blijven vertrouwelijk. De werkgever krijgt geen diagnose of onnodige medische details. Voor verzuimbegeleiding kan de bedrijfsarts binnen de geldende kaders wel noodzakelijke informatie geven over functionele mogelijkheden, passende werkaanpassingen en de verwachte verzuimduur.',
      'Een bezoek aan de bedrijfsarts is niet hetzelfde als een bezoek aan de huisarts: de bedrijfsarts beoordeelt de relatie tussen gezondheid en werk en adviseert over preventie en werkmogelijkheden. Een werknemer kan de bedrijfsarts ook raadplegen zonder ziekmelding.',
      'Voor het PAGO adviseert de bedrijfsarts over inhoud en frequentie op basis van arbeidsrisico’s. Informatie over blootstelling, werkorganisatie of fysieke belasting kan vanuit andere deskundigheid worden ingebracht; dat maakt de beoordeling geen rigide taakverdeling.',
    ],
    practicalPoints: [
      'regel in het basiscontract hoe werknemers rechtstreeks en preventief toegang krijgen;',
      'maak verzuimbegeleiding, PAGO, preventieve advisering en signalering van beroepsziekten bespreekbaar;',
      'vraag geen diagnose of individueel medisch dossier op bij de bedrijfsarts;',
      'gebruik alleen passende, niet-herleidbare groepssignalen voor preventie en de RI&E;',
      'betrek andere arbodeskundigen wanneer technische, organisatorische of blootstellingsrisico’s dat vragen.',
    ],
    rieRelationship: 'Niet-herleidbare patronen uit de bedrijfsartspraktijk kunnen aanleiding zijn om risico’s of maatregelen in de RI&E opnieuw te beoordelen. Individuele diagnoses en medische dossiers horen niet in de RI&E. Bij vergelijkbare arm- en schouderklachten kan de bedrijfsarts de betrokken werknemer vertrouwelijk beoordelen; op organisatieniveau kan de werkgever vervolgens onderzoeken of werkbelasting, hulpmiddelen of herstelmogelijkheden aandacht vragen, zonder individuele medische informatie te ontvangen.',
    supportWhen: 'Vraag de bedrijfsarts om medische of arbeidsgezondheidskundige duiding, advies over preventie, PAGO of wettelijke arbodienstverlening. Bespreek vermoedelijke beroepsziekten met de bedrijfsarts, inclusief hoe signalering en melding zijn geregeld; de werkgever stelt zelf geen medische diagnose vast. Voor specialistische niet-medische risicoanalyse kan andere kerndeskundigheid nodig zijn.',
    nextStep: 'Controleer of uw basiscontract de wettelijk vereiste taken duidelijk beschrijft en werknemers weten hoe zij rechtstreeks contact kunnen opnemen. Behandel bij individuele begeleiding alleen de noodzakelijke functionele informatie die de bedrijfsarts binnen de geldende kaders deelt. Formuleer organisatievragen over werkzaamheden, belasting en preventie, niet over diagnoses. Spreek af wie niet-herleidbare adviezen op organisatieniveau ontvangt en hoe preventieve acties worden gevolgd. De werkgever blijft verantwoordelijk voor de organisatie en maatregelen op het werk.',
    legalContext: 'Artikel 14 van de Arbowet regelt deskundige ondersteuning bij wettelijke arbotaken, waaronder verzuimbegeleiding, het toetsen en adviseren over de RI&E, PAGO en preventieve advisering. In het basiscontract worden afspraken vastgelegd over deze ondersteuning, rechtstreekse toegang tot de bedrijfsarts en professionele onafhankelijkheid. Artikel 18 regelt het periodiek aanbieden van PAGO; de bedrijfsarts adviseert over inhoud en frequentie op basis van arbeidsrisico’s. Werknemers moeten de bedrijfsarts rechtstreeks en zonder toestemming kunnen bezoeken met vragen over gezondheid in relatie tot werk, ook zonder ziekmelding. Medische informatie blijft vertrouwelijk.',
    additionalFaq: { question: 'Wie betaalt een bezoek aan de bedrijfsarts?', answer: 'De werkgever organiseert en bekostigt de wettelijk vereiste arbodienstverlening. Voor werknemers mag preventieve toegang geen onnodige financiële of organisatorische drempel hebben. De reden voor contact blijft vertrouwelijk.' },
  },
  'wat-is-psychosociale-arbeidsbelasting': {
    shortAnswer: 'Psychosociale arbeidsbelasting (PSA) omvat arbeidsrisico’s die stress kunnen veroorzaken. De hoofdvormen zijn werkdruk en ongewenst gedrag, waaronder agressie, geweld, pesten, discriminatie en seksuele intimidatie. Stressklachten hoeven niet eerst te zijn ontstaan voordat een risico wordt aangepakt.',
    relevantWhen: 'Onderzoek PSA-risico’s bij signalen van hoge werkdruk, ongewenst gedrag, uitval, terugkerende conflicten of veranderingen in werk en organisatie. Een conflict is niet automatisch PSA, maar terugkerende of escalerende conflicten kunnen aanleiding zijn om sociale veiligheid, leiderschap, werkorganisatie en gedrag nader te onderzoeken.',
    practiceExample: 'Een klantenserviceteam meldt stress en verbaal geweld. Alleen een weerbaarheidstraining pakt de oorzaken niet volledig aan. De organisatie onderzoekt ook targets, pauzes, bezetting, escalatiemogelijkheden, opvang na incidenten en de manier waarop leidinggevenden meldingen opvolgen.',
    context: [
      'Werkdruk kan samenhangen met hoeveelheid of complexiteit van werk, onduidelijke prioriteiten, beperkte regelruimte, onvoldoende herstel, onderbezetting, tegenstrijdige verwachtingen, emotionele belasting, voortdurende bereikbaarheid of gebrek aan steun en feedback. Dit zijn voorbeelden, geen limitatieve wettelijke lijst.',
      'Ongewenst gedrag omvat onder meer agressie, geweld, pesten, discriminatie en seksuele intimidatie. Beoordeel niet alleen losse gebeurtenissen, maar ook patronen, omstandigheden en de manier waarop meldingen worden opgevolgd.',
      'Stress kan ook andere oorzaken hebben. Voor PSA gaat het om arbeidsrisico’s die stress kunnen veroorzaken; daadwerkelijke klachten zijn geen voorwaarde om preventief risico’s te beoordelen. Een medewerkeronderzoek kan signalen geven, maar vervangt geen analyse van oorzaken, risicogroepen, maatregelen en opvolging.',
      'Een vertrouwenspersoon kan vertrouwelijke opvang en bespreking van ongewenst gedrag bieden, maar vervangt geen preventief organisatiebeleid. Onderzoek patronen op groeps- en organisatieniveau en bied daarnaast een veilige route voor individuele meldingen en hulpvragen. Spreek af hoe opvolging, vertrouwelijkheid en bescherming tegen benadeling worden geregeld; beloof geen absolute anonimiteit.',
    ],
    practicalPoints: [
      'beoordeel in de RI&E welke functies en groepen risico lopen, waardoor dat komt en onder welke omstandigheden;',
      'beoordeel bestaande maatregelen en hun effectiviteit en vertaal de uitkomst naar concrete acties in het plan van aanpak;',
      'pak waar mogelijk bronnen in werkorganisatie, bezetting, leiderschap en omgangsvormen aan;',
      'bied veilige individuele meld- en hulpvragenroutes naast analyse van groepspatronen;',
      'zet training, campagnes of een meldpunt aanvullend in; die vervangen bronmaatregelen niet automatisch.',
    ],
    rieRelationship: 'De RI&E beoordeelt PSA-risico’s ook wanneer nog geen stressklachten zijn gemeld. Breng relevante functies en groepen, oorzaken, omstandigheden, bestaande maatregelen en hun effectiviteit in beeld. Leg in het plan van aanpak vast welke preventie- of beperkingsmaatregelen worden uitgevoerd, wie dit doet en hoe het resultaat wordt geëvalueerd. Betrek werknemers bij de analyse zonder hen te dwingen persoonlijke ervaringen openbaar te maken.',
    supportWhen: 'De deskundigheid hangt af van de vraag en is informatief bedoeld. Een arbeids- en organisatiedeskundige kan helpen bij organisatiebrede PSA, werkdruk, leiderschap, samenwerking en sociale veiligheid. De bedrijfsarts richt zich op individuele gezondheid, ziekte, belastbaarheid en werkgerelateerd verzuim. Een arbeidspsycholoog kan individuele psychologische begeleiding bieden; een vertrouwenspersoon biedt opvang en bespreking van ongewenst gedrag; een arbeidsrechtjurist kan juridische arbeids- of discriminatievragen beoordelen. Geen van deze rollen bepaalt op zichzelf de hele aanpak.',
    nextStep: 'Combineer signalen uit gesprekken, verzuim, incidenten en medewerkeronderzoek zorgvuldig. Onderzoek daarna welke kenmerken van het werk de belasting veroorzaken en welke groepen of functies daarmee te maken hebben. Leg risico’s, bestaande maatregelen, opvolging en effect in de RI&E en het plan van aanpak vast. Maak individuele meldroutes bekend, spreek af wie meldingen opvolgt en hoe vertrouwelijkheid en bescherming tegen benadeling worden geborgd. Betrek werknemers bij oorzaken en uitvoerbaarheid. Toets na invoering of de maatregelen de oorzaken en werksituatie daadwerkelijk verbeteren.',
    legalContext: 'Artikel 3, tweede lid, van de Arbowet verplicht de werkgever beleid te voeren dat erop is gericht psychosociale arbeidsbelasting te voorkomen en, als dat niet mogelijk is, te beperken. Artikel 2.15 van het Arbobesluit werkt dit uit: als werknemers aan PSA worden of kunnen worden blootgesteld, moeten de risico’s in de RI&E worden beoordeeld en moeten in het plan van aanpak passende maatregelen worden vastgesteld en uitgevoerd. Ook hoort voorlichting te worden gegeven.',
    additionalFaq: { question: 'Kan een medewerkeronderzoek de PSA-beoordeling vervangen?', answer: 'Niet volledig. Een onderzoek kan signalen geven, maar de organisatie moet ook oorzaken, risicogroepen, bestaande maatregelen en concrete opvolging beoordelen. Herhaal de beoordeling na belangrijke veranderingen of incidenten.' },
  },
  'wanneer-arbeidsongeval-melden': {
    relevantWhen: 'Beoordeel dit onmiddellijk na een ongeval en opnieuw zodra later informatie ontstaat over ziekenhuisopname of blijvend letsel. De meldplicht kan ook gelden voor uitzendkrachten en andere personen die onder gezag van de organisatie werken.',
    practiceExample: 'Na een val lijkt het letsel eerst beperkt, maar later volgt een ziekenhuisopname voor behandeling. De werkgever meldt het ongeval zodra die opname bekend is, bewaart relevante feiten en voorkomt dat intern onderzoek de verplichte melding of hulpverlening vertraagt.',
    rieRelationship: 'Een ongeval toont mogelijk dat een risico, werkwijze of maatregel in de RI&E onvolledig of onvoldoende effectief is. Gebruik de feiten en onderzoeksuitkomsten daarom om de RI&E en het plan van aanpak bij te werken, naast de afzonderlijke meld- en registratieverplichtingen.',
    supportWhen: 'Neem bij twijfel contact op met de Nederlandse Arbeidsinspectie en meld volgens de officiële route. Juridische of veiligheidskundige ondersteuning kan verstandig zijn bij ernstige gebeurtenissen, complexe arbeidsrelaties of onderzoek, maar mag een directe melding nooit vertragen.',
    nextStep: 'Verleen direct hulp en voorkom nieuw gevaar. Controleer daarna of sprake is van overlijden, ziekenhuisopname of blijvend letsel en meld onmiddellijk via de officiële kanalen wanneer een criterium geldt. Wacht niet op een intern onderzoek of volledige zekerheid; bij twijfel kan de Arbeidsinspectie de meldingsplicht beoordelen. Leg feiten, betrokken arbeidsrelatie en later bekend geworden letsel zorgvuldig vast. Beperk wijzigingen aan de plaats van het ongeval wanneer onderzoek kan volgen. Start daarnaast een passende interne evaluatie en verwerk relevante lessen in de RI&E en het plan van aanpak.',
    additionalFaq: { question: 'Moet een ongeval met een uitzendkracht worden gemeld?', answer: 'Dat kan. De meldplicht ziet ook op personen die onder gezag werken. Stem verantwoordelijkheden snel af, maar laat onduidelijkheid een noodzakelijke melding niet vertragen.' },
  },
  'wat-doet-een-arbeidshygienist': {
    shortAnswer: 'Een arbeidshygiënist beoordeelt gezondheidsrisico’s door blootstelling tijdens het werk en adviseert over maatregelen om die blootstelling te voorkomen of te beheersen.',
    relevantWhen: 'Arbeidshygiënische expertise is relevant wanneer werkzaamheden blootstelling kunnen geven aan bijvoorbeeld gevaarlijke stoffen, stof, dampen, geluid, trillingen, biologische agentia, klimaat of binnenlucht en nog niet duidelijk is hoe groot of beheerst het risico is.',
    practiceExample: 'Bij een schoonmaakproces ruiken medewerkers regelmatig oplosmiddelen. De arbeidshygiënist onderzoekt producten, hoeveelheden, ventilatie, taakduur en piekmomenten. Pas daarna wordt bepaald of metingen nodig zijn en welke bron- of collectieve maatregelen voorrang krijgen.',
    context: [
      'De beoordeling brengt werkzaamheden, bronnen, blootstellingsroutes, duur en frequentie, betrokken werknemers of groepen, mogelijke gezondheidseffecten en bestaande maatregelen met elkaar in verband. Stoffen kunnen worden ingeademd, via de huid worden opgenomen of worden ingeslikt; ook geluid, trillingen, biologische agentia, klimaat, binnenlucht en stof vragen om een passende beoordelingsmethode. Specifieke stralingsvragen kunnen aanvullende deskundigheid of eisen kennen.',
      'Een arbeidshygiënist begint niet automatisch met meten. Productinformatie en veiligheidsinformatiebladen, proceskennis, taakduur, ventilatie, blootstellingsroutes, bestaande maatregelen, eerdere metingen en vergelijkbare scenario’s kunnen eerst voldoende inzicht geven. De beoordeling kan kwalitatief of kwantitatief zijn.',
      'Een meting is alleen zinvol wanneer de vraag, meetstrategie en interpretatie vooraf duidelijk zijn. De uitkomst wordt beoordeeld aan de hand van toepasselijke grens- of advieswaarden en andere passende criteria. Niet iedere arbeidsfactor heeft één universele wettelijke grenswaarde; leg aannames en meetonzekerheid navolgbaar vast.',
      'Een arbeidshygiënist is geen arts: deze deskundige richt zich op blootstelling en beheersmaatregelen. De bedrijfsarts behandelt individuele gezondheids- en arbeidsgezondheidskundige vragen. Een ergonoom richt zich op fysieke belasting en de relatie tussen mens, taak en werkplek; een specialist gevaarlijke stoffen kan adviseren over stofeigenschappen, opslag, etikettering en chemisch beheer. Deze expertises kunnen overlappen en samenwerken.',
      'De beoordeling van een groep of blootstelling is geen medische conclusie over een individuele werknemer. Vragen over individuele gezondheid, belastbaarheid of beroepsziekte horen bij de bedrijfsarts.',
    ],
    practicalPoints: [
      'breng werkzaamheden, bronnen, blootstellingsroutes, duur en frequentie in kaart;',
      'verzamel productinformatie, veiligheidsinformatiebladen, proces- en ventilatiegegevens en eerdere metingen;',
      'beoordeel zowel representatieve werkzaamheden als onderhoud, storingen en pieksituaties;',
      'beoordeel blootstelling kwalitatief of kwantitatief met passende criteria; meet alleen met een duidelijke strategie en interpretatie;',
      'kies maatregelen volgens de arbeidshygiënische strategie: eerst bronaanpak, daarna collectieve technische of organisatorische maatregelen en waar nodig PBM voor restrisico’s.',
    ],
    rieRelationship: 'Een verdiepende arbeidshygiënische beoordeling kan de RI&E helpen onderbouwen: welke blootstelling bestaat, welke aannames of meetgegevens zijn gebruikt, welke toepasselijke grens- of advieswaarden gelden en welke maatregelen prioriteit hebben. Beoordeel daarna of de maatregelen worden uitgevoerd en de blootstelling voldoende beheersen. Bij gevaarlijke stoffen moeten de aard, mate en duur van mogelijke blootstelling worden beoordeeld; een meting is één mogelijke methode naast onderbouwde schattingen of vergelijkbare situaties.',
    supportWhen: 'Vraag ondersteuning als de bestaande informatie geen betrouwbare blootstellingsbeoordeling oplevert, specialistische meetstrategie nodig is of beheersmaatregelen moeten worden beoordeeld. De arbeidshygiënist kan werkzaamheden en groepen beoordelen, maar stelt geen individuele medische diagnose. Voor gezondheid, belastbaarheid, PAGO of mogelijke beroepsziekte betrekt u de bedrijfsarts. Specifieke vragen over straling kunnen aanvullende deskundigheid of eisen kennen; beoordeel die apart aan de hand van de betrokken stralingssoort en werkzaamheden.',
    nextStep: 'Beschrijf per taak welke producten, processen en apparatuur worden gebruikt, wie eraan werkt en hoe lang en hoe vaak blootstelling kan optreden. Verzamel veiligheidsinformatiebladen, eerdere meetrapporten, gegevens over ventilatie en bestaande maatregelen. Neem ook onderhoud, schoonmaak, storingen en piekmomenten mee. Vraag vervolgens welke beoordelingsmethode past en welke criteria gelden. Laat de deskundige uitleggen waarom een meting nodig is of waarom bestaande informatie volstaat. Leg maatregelen volgens de arbeidshygiënische strategie vast en controleer later of ze in de praktijk werken.',
    legalContext: 'De Arbowet verlangt dat arbeidsrisico’s worden beoordeeld en dat blootstelling zo veel mogelijk wordt voorkomen of beheerst. Voor gevaarlijke stoffen moeten aard, mate en duur van blootstelling worden beoordeeld; afhankelijk van stof, factor, werk en blootstellingssituatie gelden specifieke voorschriften en grenswaarden. De arbeidshygiënische strategie geeft voorrang aan maatregelen aan de bron, daarna collectieve technische of organisatorische maatregelen en pas waar nodig persoonlijke beschermingsmiddelen voor restrisico’s. Passende deskundige ondersteuning helpt de werkgever, die verantwoordelijk blijft voor de maatregelen.',
    additionalFaq: { question: 'Wat is het verschil met een bedrijfsarts?', answer: 'De arbeidshygiënist beoordeelt blootstelling en beheersing in de werkomgeving. De bedrijfsarts beoordeelt medische en arbeidsgezondheidskundige vragen binnen het beroepsgeheim. Beide disciplines kunnen elkaar aanvullen. Meetonzekerheid blijft daarbij altijd expliciet zichtbaar.' },
  },
  'wanneer-incidentonderzoek-zinvol': {
    shortAnswer: 'Onderzoek incidenten wanneer feiten, oorzaken of verbetermaatregelen niet duidelijk zijn, bij ernstige of herhaalde gebeurtenissen en bij bijna-ongevallen met groot potentieel. De wettelijke meldings-, registratie- en medewerkingsplichten zijn een aparte kwestie.',
    relevantWhen: 'Onderzoek is zinvol bij ernstige of herhaalde incidenten, bijna-ongevallen met grote mogelijke gevolgen en situaties waarin oorzaken of effectieve maatregelen niet duidelijk zijn. Niet ieder bijna-ongeval vraagt dezelfde diepgang: weeg feitelijke en mogelijke ernst, herhaling, onzekerheid, leerpotentieel en aanwijzingen dat barrières ontbraken of faalden.',
    practiceExample: 'Een machinebeveiliging wordt tijdelijk overbrugd om een storing op te lossen. Onderzoek niet alleen wie dit deed, maar ook waarom overbruggen op dat moment mogelijk, aantrekkelijk of noodzakelijk leek: hoe vaak trad de storing op, was er productiedruk, kon de taak veilig worden uitgevoerd, waren procedures en toezicht werkbaar en boden ontwerp en onderhoud voldoende bescherming? Beoordeel ook waarom technische en organisatorische barrières het overbruggen niet voorkwamen. Stel de machine buiten gebruik totdat een bevoegde beoordeling bevestigt dat zij weer veilig kan worden ingezet; herstel en toets de beveiliging voordat het werk wordt hervat.',
    context: [
      'Een intern leeronderzoek is niet hetzelfde als een onderzoek door een externe incidentonderzoeker. Er is geen algemene wettelijke verplichting om ieder incident extern te laten onderzoeken. Voor bepaalde arbeidsongevallen gelden wel directe meldings-, registratie-, medewerkings- en onderzoeksverplichtingen.',
      'De Arbeidsinspectie vraagt de ongevalssituatie zo veel mogelijk ongewijzigd te laten en betrokkenen en getuigen te horen. Werkgever en werknemers moeten volledig meewerken en gevraagde informatie geven. Helpverlening en het voorkomen van verder gevaar gaan voor; leg daarna relevante feiten tijdig vast.',
      'Na de eerste beoordeling vraagt de Arbeidsinspectie de werkgever doorgaans zelf onderzoek te doen en hierover een werkgeversrapportage met verbeterplan op te stellen. De Inspectie kan uitzonderlijk zelf verder onderzoek doen, bijvoorbeeld bij een dodelijk ongeval of een ongeval met een kind van 15 jaar of jonger of een jeugdige van 16 of 17 jaar. Als de rapportage of het verbeterplan onvoldoende is, kan de Inspectie ook zelf verder onderzoek doen.',
      'Bepaal vooraf het doel en de reikwijdte: leren en herhaling voorkomen is iets anders dan een formele werkgeversrapportage of onderzoek volgens aanwijzingen van de Arbeidsinspectie. Houd die doelen herkenbaar naast elkaar. Regel eerst noodzakelijke hulp, rust of begeleiding; vraag betrokkenen niet onnodig meteen om verklaringen. Betrek daarna mensen die het werk kennen, bied ruimte om hun ervaring te delen en trek geen conclusie over schuld voordat relevante omstandigheden en barrières zijn onderzocht.',
      'Kies deskundigheid naar de vraag, zonder vaste route te veronderstellen. Een MVK kan passen bij een afgebakende operationele veiligheidsvraag; een HVK bij complexe of organisatiebrede oorzaken; een onafhankelijke incidentonderzoeker bij ernstige, gevoelige of multidisciplinaire zaken. Een machineveiligheidsdeskundige kan technische beveiligingen beoordelen en een arbeidshygiënist blootstelling. Onderzoek en veiligheidskundige analyse kunnen ook onderdeel zijn van de passende MVK- of HVK-inzet.',
    ],
    practicalPoints: [
      'Verleen eerst hulp, voorkom verder gevaar en stel de werkplek veilig; noodzakelijke hulp en veiligheid gaan vóór het bewaren van de situatie.',
      'Controleer direct of melden aan de Arbeidsinspectie verplicht is en volg de meldroute en eventuele aanwijzingen.',
      'Laat de ongevalssituatie daarna zo veel mogelijk ongewijzigd; leg vast wat voor hulp of veiligheid toch moest veranderen.',
      'Leg tijdig controleerbare feiten vast over taak, apparatuur, omstandigheden, planning, procedures en eerdere signalen; scheid waarnemingen van aannames.',
      'Bepaal vooraf of het doel leren, een formele rapportage of beide is en wie de uitkomsten nodig heeft.',
      'Kies een proportionele onderzoeksdiepte op basis van mogelijk gevolg, herhaling, onzekerheid en aanwijzingen van de toezichthouder.',
      'Onderzoek directe én achterliggende oorzaken: kijk naar barrières, ontwerp, onderhoud, werkdruk, organisatie en dagelijkse praktijk, en betrek betrokkenen zonder vooraf schuld toe te wijzen.',
      'Vertaal bevindingen naar concrete maatregelen, een verantwoordelijke en een haalbare termijn; geef eerst voorrang aan het wegnemen van de bron of het verbeteren van barrières.',
      'Controleer uitvoering en effect. Beoordeel of de RI&E of het plan van aanpak aanpassing nodig heeft wanneer nieuwe feiten aantonen dat risico’s, maatregelen of prioriteiten ontbreken of niet werken.',
    ],
    rieRelationship: 'Beoordeel na onderzoek of de nieuwe feiten gevolgen hebben voor de RI&E of het plan van aanpak. Pas deze aan wanneer een risico, blootstelling, taak, prioriteit of maatregel ontbreekt of aantoonbaar niet werkt; een incident betekent niet automatisch dat de volledige RI&E opnieuw moet. Leg relevante wijzigingen en opvolging navolgbaar vast. Houd verbeterleren apart van wettelijke meldings- en registratieregels en volg aanwijzingen van de Nederlandse Arbeidsinspectie.',
    supportWhen: 'Kies ondersteuning op basis van ernst, gevoeligheid, onzekerheid en benodigde deskundigheid. Een MVK kan passen bij een overzichtelijke operationele vraag; een HVK bij samenhangende of organisatiebrede veiligheidsvraagstukken. Een onafhankelijke incidentonderzoeker kan passend zijn bij een ernstig, gevoelig of multidisciplinair onderzoek. Schakel een machineveiligheidsdeskundige in voor technische beveiligingen en een arbeidshygiënist voor blootstellingsvragen. Deze voorbeelden zijn een oriëntatie, geen verplichte verwijzing: onderzoek en veiligheidskundige analyse kunnen ook bij de passende MVK- of HVK-inzet horen. Bij een meldingsplichtig arbeidsongeval volgt u de werkwijze en aanwijzingen van de Arbeidsinspectie; onderzoek mag hulpverlening, directe melding of medewerking niet vertragen.',
    nextStep: 'Bepaal eerst of hulpverlening, veiligstelling of directe melding nodig is. Een arbeidsongeval moet direct worden gemeld bij overlijden, ziekenhuisopname of blijvend letsel; blijkt opname of blijvend letsel later, meld dan direct zodra dit bekend is. Ook een (dag)opname van enkele uren kan meetellen. De werkgever houdt daarnaast een afzonderlijke registratie bij van alle gemelde arbeidsongevallen en ongevallen met meer dan drie dagen verzuim. Lees ook wanneer u een arbeidsongeval moet melden. Leg daarna feiten tijdig vast, kies een proportionele onderzoeksdiepte en onderzoek ook waarom technische of organisatorische barrières niet werkten. De Arbeidsinspectie kan de werkgever vragen een rapportage en verbeterplan op te stellen; volg de officiële instructies en controleer dat maatregelen worden uitgevoerd.',
    legalContext: 'Er is geen algemene wettelijke verplichting om ieder incident door een externe incidentonderzoeker te laten onderzoeken. Artikel 9 van de Arbowet verplicht werkgevers arbeidsongevallen direct te melden wanneer sprake is van overlijden, ziekenhuisopname of blijvend letsel; ook later bekend geworden ziekenhuisopname of blijvend letsel moet direct worden gemeld zodra dit bekend is. Een dagopname van enkele uren, bijvoorbeeld voor een operatie of ingreep, kan ook als ziekenhuisopname gelden. Registratie is iets anders dan directe melding: alle gemelde ongevallen en ongevallen met meer dan drie dagen verzuim worden geregistreerd. Na een melding onderzoekt de Arbeidsinspectie de situatie eerst zelf en vraagt zij de werkgever doorgaans om verder onderzoek, een werkgeversrapportage en verbeterplan. In uitzonderingsgevallen doet de Inspectie zelf verder onderzoek.',
    additionalFaq: { question: 'Wat is het verschil tussen een feitenonderzoek en een schuldvraag?', answer: 'Een leergericht feitenonderzoek onderzoekt omstandigheden en barrières. Juridische verantwoordelijkheid kan apart relevant zijn, maar mag het verzamelen van bruikbare veiligheidslessen niet voortijdig vernauwen.' },
  },
} as const

type ArticleSlug = keyof typeof articleEnhancements

type ArticleInput = Omit<KnowledgeArticleContent, 'type' | 'status' | 'validationStatus' | 'evidenceLevel' | 'lastReviewed' | 'metadata' | 'faq' | 'relevantWhen' | 'practiceExample' | 'rieRelationship' | 'supportWhen' | 'nextStep' | 'slug'> & {
  slug: ArticleSlug
  faq: readonly [{ question: string; answer: string }, { question: string; answer: string }]
}
function article(input: ArticleInput): KnowledgeArticleContent {
  const { additionalFaq, ...enhancement } = articleEnhancements[input.slug]
  const contentReviewedOnCurrentDate = ['wanneer-bedrijfsarts-inschakelen', 'wat-is-psychosociale-arbeidsbelasting', 'wat-doet-een-arbeidshygienist', 'wanneer-incidentonderzoek-zinvol'].includes(input.slug)
  return { ...input, ...enhancement, type: 'knowledge', status: 'PUBLISHED', validationStatus: input.slug === 'moet-ik-een-rie-hebben' ? 'VALIDATED' : 'CONTEXT_DEPENDENT', evidenceLevel: 'AUTHORITATIVE', lastReviewed: input.slug === 'wat-doet-een-preventiemedewerker' ? '2026-09-21' : contentReviewedOnCurrentDate ? '2026-09-22' : '2026-07-24', metadata: { title: `${input.title} | WorkMatchr`, description: input.summary }, faq: [...input.faq, additionalFaq].map((item, index) => ({ id: `${input.slug}-faq-${index + 1}`, ...item })) }
}

export const knowledgeArticles = [
  article({ id: 'knowledge:rie-required', slug: 'moet-ik-een-rie-hebben', title: 'Moet ik een RI&E hebben?', href: publicRoutes.rieQuestion, summary: 'Heeft uw organisatie personeel, dan moet u als werkgever in beginsel een schriftelijke RI&E met plan van aanpak hebben.', shortAnswer: 'Heeft uw organisatie personeel, dan geldt in beginsel de RI&E-verplichting. Uw arbeidsrelaties, branche, personeelsomvang en gebruikte instrument bepalen hoe u de RI&E uitvoert en of toetsing nodig is.', context: ['De RI&E beschrijft de gevaren en risico’s van het werk, bestaande maatregelen en bijzondere groepen werknemers. Het plan van aanpak maakt er onderdeel van uit.', 'Onder personeel kunnen ook andere werkrelaties vallen dan werknemers met een vast contract. Laat twijfel over uw concrete situatie gericht beoordelen.'], practicalPoints: ['beschrijf de echte werkzaamheden, locaties en groepen;', 'gebruik geen algemene checklist als eindpunt;', 'maak maatregelen, termijnen en verantwoordelijken concreet;', 'actualiseer bij veranderingen, incidenten en nieuwe inzichten.'], legalContext: 'Artikel 5 van de Arbowet vormt de basis. Kleine werkgevers kunnen onder voorwaarden andere toetsingsregels gebruiken, maar zijn met personeel niet automatisch vrijgesteld van een RI&E.', sourceIds: ['arbowet-current', 'arbeidsinspectie-rie', 'rijksoverheid-arbowet'], searchTerms: ['rie nodig', 'personeel', 'risico inventarisatie', 'werkgever'], faq: [{ question: 'Heb ik zonder personeel een RI&E nodig?', answer: 'Volgens Rijksoverheid niet. Laat bij twijfel wel beoordelen of personen feitelijk onder uw gezag werken.' }, { question: 'Is de RI&E eenmalig?', answer: 'Nee. Wijzigingen, ervaringen en nieuwe inzichten kunnen actualisatie nodig maken.' }] }),
  article({ id: 'knowledge:preventiemedewerker', slug: 'wat-doet-een-preventiemedewerker', title: 'Wat doet een preventiemedewerker?', href: publicRoutes.preventionOfficerQuestion, summary: 'De preventiemedewerker ondersteunt de werkgever intern bij de RI&E, het arbobeleid en preventieve maatregelen.', shortAnswer: 'De preventiemedewerker is de interne deskundige die de werkgever ondersteunt bij de RI&E, het arbobeleid en de uitvoering van preventieve maatregelen. De rol vraagt voldoende deskundigheid, tijd, middelen en een herkenbare positie. De werkgever blijft eindverantwoordelijk.', context: ['De drie wettelijke kerntaken zijn meewerken aan de RI&E, adviseren en nauw samenwerken met medezeggenschap en arbodeskundigen, en meewerken aan de uitvoering van maatregelen.', 'Externe deskundigheid kan de interne rol versterken, maar vervangt de wettelijke inrichting niet automatisch.'], practicalPoints: ['geef rechtstreeks toegang tot werkgever of management;', 'maak voor werknemers duidelijk hoe zij risico’s kunnen melden;', 'leg taken, tijd, middelen en toegang tot informatie vast;', 'organiseer overleg met OR of PVT, bedrijfsarts en arbodienst;', 'voorkom een uitsluitend administratieve rol en volg signalen en maatregelen aantoonbaar op.'], legalContext: 'Artikel 13 van de Arbeidsomstandighedenwet regelt deskundige bijstand door werknemers. Iedere werkgever met werknemers wijst ten minste één preventiemedewerker aan. Bij maximaal 25 werknemers mag de werkgever onder voorwaarden zelf de rol vervullen.', sourceIds: ['arbowet-current', 'arbeidsinspectie-preventiemedewerker', 'arboportaal-preventiemedewerker', 'arboportaal-arbozorg-organisatie', 'rijksoverheid-arbowet'], searchTerms: ['preventiemedewerker taken', 'preventie', 'interne deskundige', 'artikel 13'], faq: [{ question: 'Moet iedere werkgever een preventiemedewerker hebben?', answer: 'Iedere werkgever met werknemers moet in beginsel ten minste één preventiemedewerker aanwijzen. Bij maximaal 25 werknemers mag de werkgever onder de wettelijke voorwaarden zelf de preventietaken uitvoeren.' }, { question: 'Moet een preventiemedewerker een opleiding hebben?', answer: 'Er is geen uniforme verplichte opleiding of certificering voor iedere situatie. De preventiemedewerker moet wel voldoende kennis en ervaring hebben en voldoende tijd en middelen krijgen, passend bij de risico’s en taken.' }] }),
  article({ id: 'knowledge:bhv-capacity', slug: 'hoeveel-bhvers-heb-ik-nodig', title: 'Hoeveel BHV’ers heeft mijn organisatie nodig?', href: publicRoutes.bhvQuestion, summary: 'Er is geen vast wettelijk aantal; de BHV-organisatie moet onder alle relevante omstandigheden doeltreffend zijn.', shortAnswer: 'Bepaal het benodigde aantal en de spreiding vanuit risico’s, locaties, bezetting, werktijden en mogelijke uitval. Eén getal zonder die context is niet betrouwbaar.', context: ['De BHV moet eerste hulp, brandbestrijding, evacuatie en verbinding met hulpdiensten kunnen ondersteunen. Wat daarvoor nodig is verschilt per organisatie.', 'Vakantie, ziekte, ploegendienst, thuiswerk en meerdere locaties beïnvloeden de feitelijke beschikbaarheid.'], practicalPoints: ['gebruik de RI&E en noodscenario’s als uitgangspunt;', 'beoordeel aanwezigheid per locatie en tijdvak;', 'zorg voor middelen, alarmering, instructie en oefeningen;', 'test de organisatie en verbeter na oefeningen of incidenten.'], legalContext: 'Artikel 15 van de Arbowet verlangt doeltreffende bijstand maar noemt geen algemeen minimumaantal.', sourceIds: ['arbowet-current', 'rijksoverheid-arbowet', 'arboportaal-arbobeleid'], searchTerms: ['aantal bhv', 'bhvers', 'bedrijfshulpverlening'], faq: [{ question: 'Is één BHV’er genoeg?', answer: 'Dat kan niet zonder context worden bepaald. Afwezigheid, locaties en scenario’s moeten worden meegenomen.' }, { question: 'Moet iedere BHV’er een certificaat hebben?', answer: 'De wet stelt geen uniforme diplomaplicht, maar de taken moeten wel doeltreffend kunnen worden uitgevoerd.' }] }),
  article({ id: 'knowledge:pmo-pago', slug: 'verschil-pmo-en-pago', title: 'Wat is het verschil tussen PMO en PAGO?', href: publicRoutes.pmoPagoQuestion, summary: 'PAGO heeft een wettelijk arbeidsrisicogericht kerndoel; PMO kan ook bredere gezondheidsthema’s omvatten.', shortAnswer: 'Een PAGO richt zich op het vroeg signaleren en voorkomen van gezondheidsschade door risico’s in het werk. Een PMO kan breder zijn. Niet ieder PMO voldoet daardoor automatisch aan de PAGO-verplichting.', context: ['De RI&E vormt de basis voor de inhoud van PAGO. De bedrijfsarts adviseert over inhoud en frequentie.', 'Leefstijl- of inzetbaarheidsonderzoek kan waardevol zijn, maar vervangt het arbeidsrisicogerichte kerndoel niet zonder meer.'], practicalPoints: ['begin bij actuele arbeidsrisico’s;', 'maak doelen en vrijwilligheid duidelijk;', 'borg medische privacy en onafhankelijke uitvoering;', 'gebruik groepsuitkomsten zorgvuldig voor preventie.'], legalContext: 'Artikel 18 van de Arbowet verplicht werkgevers PAGO periodiek aan te bieden. Werknemers zijn in beginsel vrij om deel te nemen.', sourceIds: ['arbowet-current', 'arboportaal-pago', 'arboportaal-bedrijfsarts'], searchTerms: ['pmo pago verschil', 'gezondheidsonderzoek', 'preventief medisch'], faq: [{ question: 'Kan PMO aan PAGO voldoen?', answer: 'Ja, wanneer het ten minste het arbeidsrisicogerichte wettelijke doel en de relevante risico’s dekt.' }, { question: 'Mag de werkgever individuele uitslagen zien?', answer: 'Medische informatie is vertrouwelijk. Alleen verantwoorde, niet-herleidbare groepsinformatie kan voor preventie worden gebruikt.' }] }),
  article({ id: 'knowledge:occupational-physician', slug: 'wanneer-bedrijfsarts-inschakelen', title: 'Wanneer moet ik een bedrijfsarts inschakelen?', href: publicRoutes.occupationalPhysicianQuestion, summary: 'De bedrijfsarts is relevant bij preventie, gezondheid en werk, verzuim, re-integratie en wettelijke arbodienstverlening.', shortAnswer: 'Schakel de bedrijfsarts niet alleen bij verzuim in. Ook preventieve vragen, gezondheidssignalen, PAGO en advies over werkgerelateerde risico’s kunnen bedrijfsartsdeskundigheid vragen.', context: ['De bedrijfsarts adviseert onafhankelijk en bewaakt medisch beroepsgeheim. De werkgever krijgt geen diagnose.', 'Werknemers moeten de bedrijfsarts zonder onnodige drempel preventief kunnen raadplegen.'], practicalPoints: ['regel toegang en wettelijke taken in het basiscontract;', 'maak de preventieve contactroute bekend;', 'vraag advies op organisatieniveau zonder medische privacy te doorbreken;', 'betrek andere arbodeskundigen bij niet-medische risicovragen.'], legalContext: 'Artikel 14 van de Arbowet regelt deskundige bijstand. Het basiscontract bevat minimumeisen rond toegang, wettelijke taken en professionele onafhankelijkheid.', sourceIds: ['arbowet-current', 'arboportaal-bedrijfsarts', 'arboportaal-basiscontract', 'arboportaal-pago'], searchTerms: ['bedrijfsarts inschakelen', 'verzuim', 'preventief spreekuur'], faq: [{ question: 'Is de bedrijfsarts hetzelfde als de huisarts?', answer: 'Nee. De bedrijfsarts is gespecialiseerd in de relatie tussen werk en gezondheid.' }, { question: 'Mag de werkgever vragen wat iemand mankeert?', answer: 'De werkgever mag geen diagnose opvragen; de bedrijfsarts adviseert binnen medische vertrouwelijkheid over werkmogelijkheden.' }] }),
  article({ id: 'knowledge:psa', slug: 'wat-is-psychosociale-arbeidsbelasting', title: 'Wat valt onder psychosociale arbeidsbelasting?', href: publicRoutes.psaQuestion, summary: 'PSA omvat onder meer werkdruk, agressie, geweld, pesten, discriminatie en seksuele intimidatie die stress kunnen veroorzaken.', shortAnswer: 'Psychosociale arbeidsbelasting gaat over factoren in de werksituatie die stress veroorzaken. De aanpak vraagt zowel preventie bij de bron als veilige melding en ondersteuning.', context: ['Werkdruk kan ontstaan door hoeveelheid werk, complexiteit, onduidelijke prioriteiten, beperkte regelruimte of onvoldoende herstel.', 'Ongewenst gedrag vraagt duidelijke normen en opvolging, maar ook onderzoek naar organisatie, leiderschap en sociale veiligheid.'], practicalPoints: ['neem PSA expliciet op in de RI&E;', 'onderzoek oorzaken en groepen zonder individuele signalen te negeren;', 'kies bron- en organisatorische maatregelen;', 'zorg voor melding, opvang, voorlichting en evaluatie.'], legalContext: 'De Arbowet verlangt beleid om psychosociale arbeidsbelasting te voorkomen of beperken. Nadere uitwerking staat in het Arbobesluit.', sourceIds: ['arbowet-current', 'arboportaal-arbobeleid', 'arbeidsinspectie-sectoren', 'arboportaal-psa-batch2'], searchTerms: ['psa', 'werkdruk', 'pesten', 'agressie', 'sociale veiligheid'], faq: [{ question: 'Is werkstress altijd PSA?', answer: 'Stress kan meerdere oorzaken hebben. Voor PSA gaat het om relevante factoren in de arbeidssituatie.' }, { question: 'Is een vertrouwenspersoon genoeg?', answer: 'Een vertrouwenspersoon kan helpen, maar vervangt geen risicoanalyse en preventief organisatiebeleid.' }] }),
  article({ id: 'knowledge:accident-reporting', slug: 'wanneer-arbeidsongeval-melden', title: 'Wanneer moet een arbeidsongeval worden gemeld?', href: publicRoutes.accidentQuestion, summary: 'Meld een arbeidsongeval direct bij overlijden, ziekenhuisopname of blijvend letsel.', shortAnswer: 'De werkgever meldt direct wanneer het slachtoffer overlijdt, in een ziekenhuis wordt opgenomen of blijvend letsel heeft. Blijkt dit later, dan geldt de melding alsnog zodra het bekend is.', context: ['De meldingsplicht kan ook gelden voor personen die onder gezag werken, zoals uitzendkrachten of ingehuurde krachten.', 'Bij twijfel adviseert de Nederlandse Arbeidsinspectie om te melden; zij beoordeelt of het ongeval meldingsplichtig is.'], practicalPoints: ['verleen hulp en voorkom verder gevaar;', 'meld direct via de officiële kanalen;', 'bewaar de situatie en feiten waar dat veilig en nodig is;', 'registreer, werk mee aan onderzoek en vertaal lessen naar maatregelen.'], legalContext: 'Artikel 9 van de Arbowet regelt melding en registratie. De Nederlandse Arbeidsinspectie geeft actuele uitleg over criteria en werkwijze.', sourceIds: ['arbowet-current', 'arbeidsinspectie-ongevallen'], searchTerms: ['ongeval melden', 'ziekenhuis', 'blijvend letsel', 'arbeidsinspectie'], faq: [{ question: 'Telt een dagopname als ziekenhuisopname?', answer: 'De Arbeidsinspectie noemt ook een dagopname voor een ingreep of behandeling als relevante ziekenhuisopname.' }, { question: 'Wat als blijvend letsel later blijkt?', answer: 'Dan moet het ongeval alsnog direct worden gemeld zodra dit bekend is.' }] }),
  article({ id: 'knowledge:occupational-hygienist', slug: 'wat-doet-een-arbeidshygienist', title: 'Wat doet een arbeidshygiënist?', href: publicRoutes.occupationalHygienistQuestion, summary: 'Een arbeidshygiënist beoordeelt omgevingsfactoren en blootstelling die de gezondheid op het werk kunnen beïnvloeden.', shortAnswer: 'De arbeidshygiënist herkent, beoordeelt en helpt beheersen van blootstelling aan bijvoorbeeld stoffen, geluid, biologische agentia en binnenklimaat.', context: ['De deskundige begint met werkzaamheden, bronnen, duur en bestaande maatregelen en bepaalt daarna of aanvullende metingen nodig zijn.', 'Maatregelen volgen bij voorkeur de bronaanpak: eerst voorkomen of beperken aan de bron, daarna collectieve en pas later individuele bescherming.'], practicalPoints: ['beschrijf processen en blootstellingsmomenten;', 'verzamel veiligheidsinformatie en bestaande meetgegevens;', 'beoordeel representatieve én afwijkende situaties;', 'leg meetstrategie, aannames en opvolging navolgbaar vast.'], legalContext: 'De Arbowet verlangt bronaanpak en passende deskundige bijstand. Specifieke grenswaarden en voorschriften kunnen uit het Arbobesluit volgen.', sourceIds: ['arbowet-current', 'arboportaal-arbobeleid', 'arbeidsinspectie-rie', 'arboportaal-kerndeskundigen-batch2', 'arboportaal-blootstellingsmeting-batch2'], searchTerms: ['arbeidshygienist', 'blootstelling', 'stoffen', 'geluid', 'binnenklimaat'], faq: [{ question: 'Doet een arbeidshygiënist altijd metingen?', answer: 'Nee. Meten is zinvol wanneer bestaande informatie onvoldoende is voor een betrouwbare beoordeling.' }, { question: 'Is een arbeidshygiënist een arts?', answer: 'Nee. Arbeidshygiëne richt zich op blootstelling en beheersing; medische beoordeling hoort bij een bedrijfsarts.' }] }),
  article({ id: 'knowledge:incident-investigation', slug: 'wanneer-incidentonderzoek-zinvol', title: 'Wanneer is incidentonderzoek zinvol?', href: publicRoutes.incidentInvestigationQuestion, summary: 'Onderzoek incidenten wanneer de lessen nodig zijn om herhaling te voorkomen en de veiligheidsaanpak te verbeteren.', shortAnswer: 'Onderzoek is vooral zinvol als feiten, oorzaken of verbetermaatregelen niet vanzelf duidelijk zijn, bij ernstige of herhaalde incidenten en bij bijna-ongevallen met groot potentieel.', context: ['Een goed onderzoek kijkt naar technische, organisatorische en menselijke omstandigheden en vermijdt een te vroege conclusie dat één fout alles verklaart.', 'Een intern leeronderzoek staat los van de wettelijke meldingsplicht en eventuele instructies van toezichthouders.'], practicalPoints: ['maak de situatie eerst veilig en borg noodzakelijke melding;', 'verzamel feiten tijdig en zorgvuldig;', 'betrek mensen zonder schuld al vast te stellen;', 'formuleer maatregelen op bron, systeem en uitvoering en volg ze op.'], legalContext: 'Er is geen algemene plicht om ieder incident extern te laten onderzoeken. Voor ernstige arbeidsongevallen gelden wel meld-, registratie- en medewerkingsplichten.', sourceIds: ['arbowet-current', 'arbeidsinspectie-ongevallen', 'arbeidsinspectie-ongevalsonderzoek-batch2'], searchTerms: ['incidentonderzoek', 'bijna ongeval', 'oorzaakanalyse', 'leren'], faq: [{ question: 'Moet ieder bijna-ongeval worden onderzocht?', answer: 'Niet op dezelfde diepte. Ernstpotentieel, herhaling en onzekerheid bepalen welke analyse proportioneel is.' }, { question: 'Kan onderzoek wachten tot later?', answer: 'Feiten en herinneringen kunnen snel verloren gaan. Start daarom tijdig, zonder hulpverlening of wettelijke processen te hinderen.' }] }),
] as const satisfies readonly KnowledgeArticleContent[]

export function getKnowledgeArticleBySlug(slug: string): KnowledgeArticleContent | undefined { return knowledgeArticles.find((item) => item.slug === slug) }
